### ISSUE TITLE
Extremely slow when using a query string

### ISSUE THREAD

**Issue by cbaconnier** [ARCANEDEV/Localization#103]
- Localization Version: 1.2
- Laravel Version: 5.4
- PHP Version: 7.0

### Description:
Hi,
When I'm using a query string, the loading time of a page can take between 3 to 8 seconds when I use the `localsNavabar()` method in my views.
For what I have noticed with an url like this:
`http://localhost:8000/en/dashboard/users?page=2`

Localization is trying to find the corresponding route but don't succeed. So, for what I understood, it will try every known urls until it find the right one(?)

I'm working on a large application and I have several hundreds of urls and multiple languages. 

1. Is this behavior normal?  
2.  Can we ignore the query string, so it won't be a problem to find the route?
3. Any other suggestion?

### Steps To Reproduce:
Route :
 `Route::transGet('url.dashboard.users.index', 'UserController@index')->name('dashboard.users.index');`
Translation : 
`return [ 'dashboard' => ['index' => 'dashboard/users'] ]`

Navbar : 

    <div class="ui dropdown item">
        {{ I18n::getCurrentLocale() }}<i class="dropdown icon"></i>
    	<div class="menu">
        	@foreach($supportedLocales as $key => $locale)
            	<a href="{{ localization()->getLocalizedURL($key) }}" class="item" rel="alternate" hreflang="{{ $key  }}">{{ $key }}</a>
        	@endforeach
    	</div>
	</div>

1. Then, add several hundreds of urls. Note the time of 3-8 seconds. 
2. Call twice `localsNavar()`, the loading time will increase by another 3-8 seconds for a total of 6 to 16 seconds.

### Additional information
Here the method that take a huge load time
```
        /**
     * Returns the translated route for an url and the attributes given and a locale
     *
     * @param  string  $url
     * @param  array   $attributes
     * @param  string  $locale
     *
     * @return string|false
     */
    private function findTranslatedRouteByUrl($url, $attributes, $locale)
    {
        if (empty($url)) return false;

        // check if this url is a translated url
        foreach ($this->routeTranslator->getTranslatedRoutes() as $translatedRoute) {
            $translatedUrl = $this->getUrlFromRouteName($locale, $translatedRoute, $attributes);

            if ($this->getNonLocalizedURL($translatedUrl) === $this->getNonLocalizedURL($url))
                return $translatedRoute;
        }

        return false;
    }
```
[edit on 2017-13-12]  : wrong additional information

**Comment by cbaconnier** [comment]
So, I went back on this issue today. I noticed where the problem was coming from.

When we call a 404 page (for example) the method  `localization()->getLocalizedURL($key)`  will call the method `findTranslatedRouteByUrl($url, $attributes, $locale)` . 

I noticed the method `findTranslatedRouteByUrl` has a lot of recursion that will call the translations. 

With around 300 urls, 90'000+ call to `trans($key)` as been made for this request:
```
Route::get('test', function(){
    return localization()->getLocalizedURL('fr');
});
````

**Comment by arcanedev-maroc** [comment]
Ok, this is a little bit complex to solve.

The solution is to rewrite the whole the package with the new ideas that i have and it's going to solve many problems:

 * Cached localized routes.
 * Testing helpers for localized routes.
 * Reduce the middlewares to a single class.

The issue is i don't have spare time to start with a heavy dev with a fresh package. Hope it will come true in early 2018.

Best regards and thanks for using this package 👍

**Comment by cbaconnier** [comment]
Oh, I see. Thanks! Since all my routes are named, I should be able to disable this in a fork.

Best regards
