### ISSUE TITLE
Laravel 5.5 Version

### ISSUE THREAD

**Issue by Krato** [ARCANEDEV/Localization#104]
- Localization Version: 1.2
- Laravel Version: 5.5
- PHP Version: 7.1

Hello, Will be this package upgrade to Laravel 5.5?

When I try to install give me an error.

### Description:
Error on line 6  of `localization/src/Middleware/Middleware.php`.

You need to change:
```
use Arcanedev\Support\Bases\Middleware as BaseMiddleware;
```

to:
```
use Arcanedev\Support\Http\Middleware as BaseMiddleware;
```

Thanks

**Comment by arcanedev-maroc** [comment]
**PR:** #105

**Comment by arcanedev-maroc** [comment]
DONE => `v2.0.0`
