### ISSUE TITLE
Nested routes

### ISSUE THREAD

**Issue by Krato** [ARCANEDEV/Localization#106]
- Localization Version: v2.0.0
- Laravel Version: 5.5
- PHP Version: 7.1

### Description:

I'm unable to make it work with nested routes. 

### Steps To Reproduce:

This is my routes files:

`es/routes.php`:

```php
<?php

return [

    'pages' => [
        'designers'   => [
            'inicio' => 'disenadores',
            'single' => 'disenadores/{slug}',
        ],
    ],
    // other translated routes
];
```

`en/routes.php`:

```php
<?php

return [

    'pages' => [
        'designers'   => [
            'inicio' => 'designers',
            'single' => 'designers/{slug}',
        ],
    ],
    // other translated routes
];
```

And in `routes/web.php`:

```php
Route::transGet('routes.pages.designers.single', [
    'as'   => 'pages.designers.show',
    'uses' => '\App\Http\Controllers\DesignersController@show',
]);
```

When I call: `localization()->getLocalizedURL('en')` the result is:
```
http://website.on/en/disenadores/marcus
```

But it should show:
```
http://website.on/en/designers/marcus
```

**Comment by Krato** [comment]
@arcanedev-maroc Have you tested?

**Comment by arcanedev-maroc** [comment]
Hi @Krato, sorry for the wait.

I've just tested your case but i can't reproduce the issue.

This is my testing route:

```php
Route::localizedGroup(function () {
    Route::transGet('routes.pages.designers.single', function ($slug) {
        dd(
            $slug,
            localization()->getLocalizedURL('en')
        );
    })->name('pages.designers.show');
});
```

And i used the same `routes.php` lang files.

Where you did the `localization()->getLocalizedURL('en')` call ?

**Comment by Krato** [comment]
@arcanedev-maroc Just happened in one project.

Working in others. Thanks!
