### ISSUE TITLE
Many Questions regarding this package.

### ISSUE THREAD

**Issue by shirshak55** [ARCANEDEV/Localization#107]
I have cup of questions regarding this package.

Is `accept-language-header` used only for API, curl etc. I mean does it have any relation with web browser based users????

What do ` non localized root` means. Do it mean  those locales that are not written on `config/localization.php supported_locale`????

### Route
What happens if `localization-session-redirect` and `localization-cookie-redirect` both are set to true?? Will it cause both cookie and session to have current locale. By current locale I mean the locale which user is currently using. 

So if we use `localization-redirect` and set config 'hide-default-in-url'    => true. Will it redirect to same url for first time visitor

I mean if we browse url.com/dev then that localization-redirect is supposed to redirect to url.com/en/dev assuming en is default locale. And we have set hide-default-in-url config to true it means will first time user will be redirected to url.com/dev again??

By default config do it means config('app.locale') or user currently selected locale (lets say user browser locale) ?

# Middleware
It says for SEO it will redirect http://your-project-url/test to http://your-project-url/en/test . But what if we set  'hide-default-in-url'    => true ? It will redirect on same place or it do nothing for SEO??

Docs says
```
IMPORTANT - When hide-default-in-url is set to true, the unlocalized root is treated as the applications default locale app.locale. Because of this language negotiation using the Accept-Language header will NEVER occur when hide-default-in-url is true.
```
Don't use use accept-language header explicitly . I mean i will set accept-language header to `es` so  it should return Spanish languages etc.. So what it mean accept-language header will never occur when hide-default-in-url is true?

```
-------------------------------------------------------------------------------------------------------------
```

I really appreciate this package. And some of my question may be too easy . Please don't mind. As I have never done locale things it was hard for me to understand. Hope it helps other too.

Thanks

**Comment by arcanedev-maroc** [comment]
> Note: check this comment https://github.com/adr1enbe4udou1n/laravel-boilerplate/issues/4#issuecomment-333341547

Please check you're posting to the correct package.

**Comment by shirshak55** [comment]
@arcanedev-maroc  I have checked both package. I always prefer this package so I asked question here. If you check question all of it belongs to this package thats why. I have looked there also and I know that package is inspiration to this package :)

**Comment by arcanedev-maroc** [comment]
> Is `accept-language-header` used only for API, curl etc. I mean does it have any relation with web browser based users????

Yes, it's based on the user's browser, check this [article](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language).

> What do `non localized root` means. Do it mean those locales that are not written on `config/localization.php supported_locale` ????

A `non-localized root` means that doesn't have a prefix like `http://website.com/fr` or `http://website.com/es`, it's only `http://website.com => English language`

### Route

> What happens if `localization-session-redirect` and `localization-cookie-redirect` both are set to true?? Will it cause both cookie and session to have current locale. By current locale I mean the locale which user is currently using.

The `localization-session-redirect` and `localization-cookie-redirect` middlewares has the same logic (even the laravel cookies is weird to work with), save the current/selected locale and redirect the `non-localized root` to a `localized root`.

> So if we use `localization-redirect` and set config 'hide-default-in-url'    => true. Will it redirect to same url for first time visitor

> I mean if we browse url.com/dev then that localization-redirect is supposed to redirect to url.com/en/dev assuming en is default locale. And we have set hide-default-in-url config to true it means will first time user will be redirected to url.com/dev again??

I highly recommend to set the `hide-default-in-url` to `false` to avoid many problems. Read this [article](https://support.google.com/webmasters/answer/182192?hl=en) for more details.

> By default config do it means config('app.locale') or user currently selected locale (lets say user browser locale) ?

The `app.locale` is the fallback locale, if the `Localization` package can't predict the user's locale, it's going to choose the `app.locale` as the user's locale.

>`IMPORTANT - When hide-default-in-url is set to true, the unlocalized root is treated as the applications default locale app.locale. Because of this language negotiation using the Accept-Language header will NEVER occur when hide-default-in-url is true.`

> Don't use use accept-language header explicitly . I mean i will set accept-language header to `es` so  it should return Spanish languages etc.. So what it mean accept-language header will never occur when hide-default-in-url is true?

Read the [code](https://github.com/ARCANEDEV/Localization/blob/master/src/Utilities/LocalesManager.php#L340-L349)

Hope this answer all your questions 👍 

> **Note:** You can also check the answered questions [here](https://github.com/ARCANEDEV/Localization/issues?q=label%3Aquestion+is%3Aclosed) for more insights

**Comment by shirshak55** [comment]
Thank you it really helps :)
