### ISSUE TITLE
translated routes after setSupportedLocales 

### ISSUE THREAD

**Issue by carlituxman** [ARCANEDEV/Localization#11]
If use setSupportedLocales with new languages that not are in 'supported-locales' config the translated routes not work, all of possible new langs should be in supported-locales

**Comment by arcanedev-maroc** [comment]
Where did you use the `setSupportedLocales()` method ??

You need to call it before registering the routes.

**Comment by carlituxman** [comment]
in a middleware that load the langs, to change/add from a control panel

**Comment by arcanedev-maroc** [comment]
OK, as you can see, the middleware is to check/filter/other logic based on routes/requests.

So, you need to do you change/add logic about langs before that (**before registering the Localization translated routes**).

Try to put your logic inside a service provider like the [RouteServiceProvider](https://github.com/laravel/laravel/blob/master/app/Providers/RouteServiceProvider.php#L25).

Hope this helps you and let me know if its fix your issue :+1:
