### ISSUE TITLE
LocalizationKernelTrait is not longer disponible. May be update the doc?

### ISSUE THREAD

**Issue by jartaud** [ARCANEDEV/Localization#111]
- Localization Version: ^2.0
- Laravel Version: 5.5.19
- PHP Version: PHP 7.1.10-1+ubuntu17.04.1+deb.sury.org+1 (cli) (built: Sep 29 2017 17:04:49) ( NTS )

### Description:
`PHP Fatal error:  Trait 'Acme\Http\LocalizationKernelTrait' not found in /home/me/Documents/Projects/acme/app/Http/Kernel.php on line 9`

`[Symfony\Component\Debug\Exception\FatalErrorException]`   
  `Trait 'Acme\Http\LocalizationKernelTrait' not found `

### Steps To Reproduce:
phpunit or artisan serve your app

**Comment by arcanedev-maroc** [comment]
The doc is up to date, you can check these changes on [v2.1.0](https://github.com/ARCANEDEV/Localization/compare/2.0.0...2.1.0)

You can remove the `LocalizationKernelTrait` from the `app/Http/Kernel`.
