### ISSUE TITLE
Automatic redirect according to browser lang. 

### ISSUE THREAD

**Issue by hrnicek** [ARCANEDEV/Localization#118]
- Localization Version: 2.1
- Laravel Version: 5.5.34
- PHP Version: 7.1.

### Description:
Hello,

how can I redirect according to browser language? If my browser is CS(Czech), so website auto-redirect to example.com/cs, if browser EN, again auto-redirect to example.com/en.

**Comment by arcanedev-maroc** [comment]
Hi,

Make sure you add `cs` as a supported locale at [this line](https://github.com/ARCANEDEV/Localization/blob/master/config/localization.php#L10) and [accept-language-header](https://github.com/ARCANEDEV/Localization/blob/master/config/localization.php#L12) is set to `true`

You can leave the middleware as it is.

**Comment by hrnicek** [comment]
Done. :)
