### ISSUE TITLE
Locales selector menu sample

### ISSUE THREAD

**Issue by carlituxman** [ARCANEDEV/Localization#12]
Can you put a sample of a locales selector menu?

**Comment by carlituxman** [comment]
sorry is the localesNavbar function

**Comment by arcanedev-maroc** [comment]
Yes, the [Localization::localesNavbar()](https://github.com/ARCANEDEV/Localization/blob/master/src/Localization.php#L401) method.

**Comment by aketai** [comment]
Please advice how to setup Locales selector menu
I have this issue:Undefined variable: supportedLocales
Thank you
