### ISSUE TITLE
Database stored translations

### ISSUE THREAD

**Issue by karolisbarkauskas** [ARCANEDEV/Localization#121]
Hi,

can your package store model translations in database? 

if yes, what's the table structure?

**Comment by arcanedev-maroc** [comment]
There is a trait that handle translations with eloquent model but it still WIP.

Trait: https://github.com/ARCANEDEV/Localization/blob/master/src/Traits/HasTranslations.php

The table structure is the same as you do for unlocalized projects. You store the data as json text (or as json column) with something like `title = {"en": "Post title", "fr": "Titre du post"}`.

You can use a package like: https://github.com/spatie/laravel-translatable

**Comment by f-liva** [comment]
Why not use https://github.com/spatie/laravel-translatable directly?
