### ISSUE TITLE
Differences from mcamara/laravel-localization

### ISSUE THREAD

**Issue by f-liva** [ARCANEDEV/Localization#124]
Unfortunately the mcamara/laravel-localization project seems abandoned to itself and there is no way to fix quite old and limiting bugs, so I would like to move forward and looking for alternatives and I found your project that looks like a mcamara clone.

What are the differences and is this a more safe project to adopt?

**Comment by arcanedev-maroc** [comment]
Hi @fede91it,

This package is more *cleaner* and maintained compared to  `mcamara/laravel-localization`.

At first, i created this package just for my own projects. But the best way to improve it is by sharing it.

Of course this package was inspired from `mcamara/laravel-localization`, but when you start reading the code, you will notice the differences.

Check this issue #68 for more details.
