### ISSUE TITLE
getLocalizedUrl() with sluggable translation

### ISSUE THREAD

**Issue by raiika** [ARCANEDEV/Localization#126]
Could this be achieved in this repo ?

    domain.com/event/free-money  // en locale

then change language and go to

    domain.com/ja/イベント/無料のお金  // ja locale

**Comment by arcanedev-maroc** [comment]
Did you checked this section: https://github.com/ARCANEDEV/Localization/blob/master/_docs/3-Usage.md#events

**Comment by raiika** [comment]
Thank you for your response, I will try it, and I will inform you later if I found a problem or succeed.

**Comment by raiika** [comment]
Instruction unclear, what is this Event that you are calling ?

I also found out that your localizedGroup(function(){}) could not be called in RouteServiceProvider, how can I use your Router ?

**Comment by arcanedev-maroc** [comment]
You need to check if you've installed the package correctly (check also the compatible version for your laravel app) if the `localizedGroup` doesn't exists. Follow the instalation steps

The **event** feature allows you to translate the attributes (like slug) of the given route on the fly.

For more details about the laravel `events`, check the official documentation: https://laravel.com/docs/5.6/events#manually-registering-events

**Comment by raiika** [comment]
It is exist if I called it in the "routes/web.php",
But if I use it in the "RouteServiceProvider.php", it does not exist

Thanks for the information, I'll get back after I understand laravel Event
