### ISSUE TITLE
translated routes with parameters in blade?

### ISSUE THREAD

**Issue by carlituxman** [ARCANEDEV/Localization#13]
How can I use translated routes in blade with parameters?

**Comment by arcanedev-maroc** [comment]
Did you checked the docs about translated parameters ? 

https://github.com/ARCANEDEV/Localization/blob/master/_docs/4-Usage.md#events

Please, give me an example what you want to achieve.

**Comment by arcanedev-maroc** [comment]
Or you want to render translated links ?

**Comment by carlituxman** [comment]
I want render in blade

**Comment by arcanedev-maroc** [comment]
You need to require this package : https://github.com/ARCANEDEV/LaravelHtml

To install, run this command : 

``` bash
composer require arcanedev/laravel-html
```

After the installation, you need to register this package by editing the `config/app.php` file:

``` php
// config/app.php

return [
    'providers' => [
        // ...
        Arcanedev\LaravelHtml\HtmlServiceProvider::class,
    ],

    'aliases' => [
        // ...
        'Form'         => Arcanedev\LaravelHtml\Facades\Form::class,
        'Html'         => Arcanedev\LaravelHtml\Facades\Html::class,
    ],
];
```

Now you can render the translated links by their route names:

``` php
{!! link_to_route('route-name', 'Translated title', ['parameter-1', 'parameter-2', ...]) !!}
// or
{!! Html::linkToRoute('route-name', 'Translated title', ['parameter-1', 'parameter-2', ...]) !!}
```

You can do the same thing with [LaravelCollective/html](https://github.com/LaravelCollective/html) package.

> I need to add documentations to my html/form package :stuck_out_tongue_closed_eyes: .

**Comment by carlituxman** [comment]
Can I have problems with HTML of Illuminate package??

**Comment by arcanedev-maroc** [comment]
What is your laravel version ? The `illuminate/html` is not maintained anymore.

**Comment by carlituxman** [comment]
5.1

**Comment by carlituxman** [comment]
I change to laravelcollective

2015-11-07 0:04 GMT+01:00 Carlos Jiménez Mora carlos@informatik.es:

> 5.1
> El 6/11/2015 22:17, "ARCANEDEV" notifications@github.com escribió:
> 
> > What is your laravel version ?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ARCANEDEV/Localization/issues/13#issuecomment-154544110
> > .

## 

_Carlos Jiménez Mora_
_INFORMATIK SOLUCIONES_
Tlf: 950 42 62 68 - Serón (Almería)
@carlituxman https://twitter.com/carlituxman - carlos@informatik.es

_Este mensaje y sus anexos pueden contener información confidencial, por lo
que se informa de que su uso no autorizado está prohibido por la ley. Si
Vd. considera que no es el destinatario pretendido por el remitente o no
desea recibir información comercial, por favor póngalo en su conocimiento
por esta misma vía o por cualquier otro medio y elimine esta comunicación y
los anexos de su sistema, sin copiar, remitir o revelar los contenidos del
mismo a cualquier otra persona. Cualquier información, opinión, conclusión,
recomendación, etc. contenida en el presente mensaje no relacionada con la
actividad empresarial de INFORMATIK BC SOLUCIONES S.L. y/o emitida por
persona sin capacidad para ello, deberá considerarse como no proporcionada
ni aprobada por INFORMATIK BC SOLUCIONES S.L. pone los medios a su alcance
para garantizar la seguridad y ausencia de errores en la correspondencia
electrónica, pero no puede asegurar la inexistencia de virus o la no
alteración de los documentos transmitidos electrónicamente, por lo que
declina cualquier responsabilidad a este respecto._

**Comment by carlituxman** [comment]
I'm trying with LaravelCollective but how I should put the route translatable?

if translatable route is: routes.view and use:

{!! Html::linkRoute('routes.view', 'Translated title', ['parameter-1']) !!}

not work

I need to use with translatable routes with parameteres

**Comment by arcanedev-maroc** [comment]
If you want to use linkRoute() correctly, you need to specify the route names in your routes:

``` php
// app/Http/routes.php
<?php

/* ------------------------------------------------------------------------------------------------
 |  Application Routes
 | ------------------------------------------------------------------------------------------------
 */
Route::localizedGroup(function () {
    Route::get('/', [
        'as' => 'home',
        'uses' => 'PagesController@index',
    ]);

    Route::transGet('routes.about', [
        'as' => 'about-us',
        'uses' => 'PagesController@aboutUs',
    ]);

    Route::transGet('routes.view', [
        'as' => 'pages.show',
        'uses' => 'PagesController@show',
    ]);
});
```

As you can see in the last route, the `routes.view` is not the route name but its the translation key for the URL, the route name is in the key `as` = `pages.show`.

``` php
{!! Html::linkRoute('pages.show', 'Translated title', ['page-slug']) !!}
```

Check also : https://github.com/ARCANEDEV/Localization/blob/master/_docs/4-Usage.md#translated-routes

**Comment by carlituxman** [comment]
great!!!
