### ISSUE TITLE
can't install on laravel 5.6

### ISSUE THREAD

**Issue by carlituxman** [ARCANEDEV/Localization#130]
- Localization Version: 4.0.0
- Laravel Version: 5.6.38
- PHP Version: 7.1.19

### Description:
After composer require arcanedev/localization throws this error:

Problem 1
    - arcanedev/localization 4.0.0 requires arcanedev/support ~4.4.0 -> satisfiable by arcanedev/support[4.4.0].
    - Installation request for arcanedev/localization ^4.0 -> satisfiable by arcanedev/localization[4.0.0].
    - Conclusion: remove laravel/framework v5.6.38

### Steps To Reproduce:
composer require arcanedev/localizatio

**Comment by arcanedev-maroc** [comment]
You need to install the correct version.

Check this section: https://github.com/ARCANEDEV/Localization/blob/master/_docs/1-Installation-and-Setup.md#version-compatibility

**Comment by m7ammad7assan** [comment]
also this error happend to me with no solution

**Comment by arcanedev-maroc** [comment]
You need to install the correct version based on laravel version:

For example:

Install the Localization `v2.x` if you're using Laravel `v5.5` by running this command `composer require arcanedev/localization:2.x` or updating your `composer.json` file.
