### ISSUE TITLE
Translated URL not always working

### ISSUE THREAD

**Issue by nikydieben** [ARCANEDEV/Localization#139]
- Localization Version: ^4.0
- Laravel Version: ^7.1.3
- PHP Version: 5.7.*

### Description:

I did the basic setup and choosing a language works and works in my URL. I then adapted my code support the URL translation. This works, however when I try to click my navigation link to a certain page it sometimes loses the language parameter. So what I want is: http://kowloon/fr -> http://kowloon/fr/a-propos. However i get: http://kowloon/a-propos which gives a 404. If i try the same with http://kowloon/nl it works. Really confused about this

**Comment by nikydieben** [comment]
```php
//Routes

Route::localizedGroup(function () {

    Route::transGet('routes.home', function () {
        return view('pages.home');
    });

    Route::transGet('routes.about_us', function () {
        return view('pages.about_us');
    });

    Route::transGet('routes.product_list', function () {
        return view('pages.product_list');
    });

});
```

**Comment by nikydieben** [comment]
`<nav class="navbar navbar-expand-md navbar-light navbar-laravel">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            Knowloon
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>    
        <div class="collapse navbar-collapse" id="navbarSupportedContent">                
            <ul class="navbar-nav mr-auto"> 
                <li class="nav-item">
                    <a href="@lang('routes.about_us')" class="nav-link">@lang('home.about_menu')</a>
                </li>   
                <li class="nav-item">
                    <a href="@lang('routes.product_list')" class="nav-link">@lang('home.product_list_menu')</a>
                </li>                  
            </ul>
            <ul class="navbar-nav ml-auto">  
                <li class="nav-item dropdown">
                    <a id="linkDropdown" class="nav-link dropdown-toggle" href="@lang('home.lang')" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        @lang('home.language')
                        <span class="caret"></span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="nl">
                            NL
                        </a>
                        <a class="dropdown-item" href="fr">
                            FR
                        </a>
                        <a class="dropdown-item" href="ru">
                            RU
                        </a>
                    </div>
                </li>                                          
            </ul>
        </div>
    </div>
</nav>
<br>`

**Comment by arcanedev-maroc** [comment]
Can you show me how you generate the navigation menu ?

**Comment by nikydieben** [comment]
<nav class="navbar navbar-expand-md navbar-light navbar-laravel">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            Knowloon
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="@lang('routes.about_us')" class="nav-link">@lang('home.about_menu')</a>
                </li>
                <li class="nav-item">
                    <a href="@lang('routes.product_list')" class="nav-link">@lang('home.product_list_menu')</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a id="linkDropdown" class="nav-link dropdown-toggle" href="@lang('home.lang')" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        @lang('home.language')
                        <span class="caret"></span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="nl">
                            NL
                        </a>
                        <a class="dropdown-item" href="fr">
                            FR
                        </a>
                        <a class="dropdown-item" href="ru">
                            RU
                        </a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
<br>

My lang files are the same as the GitHub documentation
________________________________
Van: ARCANEDEV <notifications@github.com>
Verzonden: Tuesday, December 25, 2018 6:20:24 PM
Aan: ARCANEDEV/Localization
CC: Dieben Niky; Author
Onderwerp: Re: [ARCANEDEV/Localization] Translated URL not always working (#139)


Can you show me how you generate the navigation menu ?

**Comment by nikydieben** [comment]
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    
    <link href="{{ asset('css/owl.carousel.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/owl.theme.default.min.css') }}" rel="stylesheet">

    
    <link href="{{ asset('css/home.css') }}" rel="stylesheet">

    
    <script src="{{ asset('js/app.js') }}" defer></script>

    
    <script src="{{ asset('js/owl.carousel.min.js') }}" defer></script>
    <script src="{{ asset('js/carousel.js') }}" defer></script>

</head>
<body>
<div id="app">
    @include('layouts.nav')
    <main class="container">
        @yield('content')
    </main>
</div>

</body>
</html>


This is the base app code from my Laravel project. The nav is in the ‘@include(‘layouts.nav’)’

________________________________
Van: ARCANEDEV <notifications@github.com>
Verzonden: Tuesday, December 25, 2018 6:20:24 PM
Aan: ARCANEDEV/Localization
CC: Dieben Niky; Author
Onderwerp: Re: [ARCANEDEV/Localization] Translated URL not always working (#139)


Can you show me how you generate the navigation menu ?

**Comment by nikydieben** [comment]
Do you have a clue why this is happening?

Greetz,

________________________________
Van: ARCANEDEV <notifications@github.com>
Verzonden: Tuesday, December 25, 2018 6:20:24 PM
Aan: ARCANEDEV/Localization
CC: Dieben Niky; Author
Onderwerp: Re: [ARCANEDEV/Localization] Translated URL not always working (#139)


Can you show me how you generate the navigation menu ?

**Comment by arcanedev-maroc** [comment]
Hi @nikydieben,

This is not the correct way to generate the urls.

In my projects, i use the named routes. Something like this:

```php
Route::localizedGroup(function () {

    Route::transGet('routes.home', function () {
        return view('pages.home');
    })->name('public::index');

    Route::transGet('routes.about_us', function () {
        return view('pages.about_us');
    })->name('public::about-us');

    Route::transGet('routes.product_list', function () {
        return view('pages.product_list');
    })->name('public::products.index');

});
```
And for the nav menu:
```blade
<nav class="navbar navbar-expand-md navbar-light navbar-laravel">
    <div class="container">
        <a class="navbar-brand" href="{{ route('public::index') }}">Knowloon</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="{{ route('public::about-us') }}" class="nav-link">@lang('home.about_menu')</a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('public::products.index') }}" class="nav-link">@lang('home.product_list_menu')</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a id="linkDropdown" class="nav-link dropdown-toggle" href="@lang('home.lang')" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        @lang('home.language')
                        <span class="caret"></span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{{ localization()->getUrlFromRouteName('nl', 'public::index') }}">NL</a>
                        <a class="dropdown-item" href="{{ localization()->getUrlFromRouteName('fr', 'public::index') }}">FR</a>
                        <a class="dropdown-item" href="{{ localization()->getUrlFromRouteName('ru', 'public::index') }}">RU</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
```

Check also the documentation: https://laravel.com/docs/5.7/routing#named-routes

**Comment by nikydieben** [comment]
Hi, thanks! I will check this out!


________________________________
Van: ARCANEDEV <notifications@github.com>
Verzonden: Thursday, December 27, 2018 2:37:08 PM
Aan: ARCANEDEV/Localization
CC: Dieben Niky; Mention
Onderwerp: Re: [ARCANEDEV/Localization] Translated URL not always working (#139)


Hi @nikydieben<https://github.com/nikydieben>,

This is not the correct way to generate the urls.

In my projects, i use the named routes. Something like this:

Route::localizedGroup(function () {

    Route::transGet('routes.home', function () {
        return view('pages.home');
    })->name('public::index');

    Route::transGet('routes.about_us', function () {
        return view('pages.about_us');
    })->name('public::about-us');

    Route::transGet('routes.product_list', function () {
        return view('pages.product_list');
    })->name('public::products.index');

});

And for the nav menu:

<nav class="navbar navbar-expand-md navbar-light navbar-laravel">
    <div class="container">
        <a class="navbar-brand" href="{{ route('public::index') }}">Knowloon</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="{{ route('public::about-us') }}" class="nav-link">@lang('home.about_menu')</a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('public::products.index') }}" class="nav-link">@lang('home.product_list_menu')</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a id="linkDropdown" class="nav-link dropdown-toggle" href="@lang('home.lang')" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        @lang('home.language')
                        <span class="caret"></span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{{ localization()->getUrlFromRouteName('nl', 'public::index') }}">NL</a>
                        <a class="dropdown-item" href="{{ localization()->getUrlFromRouteName('fr', 'public::index') }}">FR</a>
                        <a class="dropdown-item" href="{{ localization()->getUrlFromRouteName('ru', 'public::index') }}">RU</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

Check also the documentation: https://laravel.com/docs/5.7/routing#named-routes
