### ISSUE TITLE
 Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Localization' not found

### ISSUE THREAD

**Issue by betterapp** [ARCANEDEV/Localization#146]
- Localization Version: 6.1
- Laravel Version: 6.4
- PHP Version: 7.2

### Description:
 Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Localization' not found

production.ERROR: Class 'Localization' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Localization' not found at routes\\web.php:16)

When make composer update
### Steps To Reproduce:
1. composer update
2. open main page

**Comment by arcanedev-maroc** [comment]
The `Localization` facade was removed.

Try to use the `localization()` helper or [Real-Time Facades](https://laravel.com/docs/6.x/facades#real-time-facades) `Facades\Arcanedev\Localization\Contracts\Localization`

**Comment by betterapp** [comment]
Can You update documentation ?

**Comment by betterapp** [comment]
How can I use it is template now in version 6 ?

**Comment by arcanedev-maroc** [comment]
Replace `Localization::` to `localization()->`

**Comment by betterapp** [comment]
It does not work with smarty

**Comment by arcanedev-maroc** [comment]
I don't encourage the use of Facade but if you insist, try to add an `aliases` in your `config/app.php`:

```php
'Localization' => Facades\Arcanedev\Localization\Contracts\Localization::class
```

What is smarty ?

**Comment by betterapp** [comment]
I use smarty as template engine

**Comment by betterapp** [comment]
Never mind. WOrking ;)
