### ISSUE TITLE
hide-default-in-url changing default locale?

### ISSUE THREAD

**Issue by carlituxman** [ARCANEDEV/Localization#15]
Is possible use hide-default-in-url set to true but can change de default locale without changing it at app.locale ?

**Comment by arcanedev-maroc** [comment]
No, i don't think so, because the default locale is the `app.locale` and it's for your whole app/packages, you can't have two default locales.

Try to use the `app.fallback_locale` as a secondary locale.

**Comment by carlituxman** [comment]
I don't want use two default locales, I want change it and when it's
changed then hide-default-in-url do it with the new default locale

**Comment by arcanedev-maroc** [comment]
OK, i see what you want to do.

You need to change the default locale before using the `LocalizationServiceProvider` and its services.

The perfect place is using a service provider like `AppServiceProvider` or creating a custom one and place the `LocalizationServiceProvider` after that in your `app.providers` config.

**Comment by carlituxman** [comment]
Do it!, I use in a provider, but I was doing setSupportedLocales() before
to change de seLocale.

now, it works!

2015-11-16 16:10 GMT+01:00 ARCANEDEV notifications@github.com:

> OK, i see what you want to do.
> 
> You need to change the default locale before using the
> LocalizationServiceProvider and its services.
> 
> The perfect place is using a service provider like AppServiceProvider or
> creating a custom one and place the LocalizationServiceProvider after that
> in your app.providers config.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ARCANEDEV/Localization/issues/15#issuecomment-157062140
> .

## 

_Carlos Jiménez Mora_
_INFORMATIK SOLUCIONES_
Tlf: 950 42 62 68 - Serón (Almería)
@carlituxman https://twitter.com/carlituxman - carlos@informatik.es

_Este mensaje y sus anexos pueden contener información confidencial, por lo
que se informa de que su uso no autorizado está prohibido por la ley. Si
Vd. considera que no es el destinatario pretendido por el remitente o no
desea recibir información comercial, por favor póngalo en su conocimiento
por esta misma vía o por cualquier otro medio y elimine esta comunicación y
los anexos de su sistema, sin copiar, remitir o revelar los contenidos del
mismo a cualquier otra persona. Cualquier información, opinión, conclusión,
recomendación, etc. contenida en el presente mensaje no relacionada con la
actividad empresarial de INFORMATIK BC SOLUCIONES S.L. y/o emitida por
persona sin capacidad para ello, deberá considerarse como no proporcionada
ni aprobada por INFORMATIK BC SOLUCIONES S.L. pone los medios a su alcance
para garantizar la seguridad y ausencia de errores en la correspondencia
electrónica, pero no puede asegurar la inexistencia de virus o la no
alteración de los documentos transmitidos electrónicamente, por lo que
declina cualquier responsabilidad a este respecto._

**Comment by arcanedev-maroc** [comment]
Cool :+1:
