### ISSUE TITLE
do not install with laravel 8

### ISSUE THREAD

**Issue by betterapp** [ARCANEDEV/Localization#156]
- Localization Version: 8
- Laravel Version: 8
- PHP Version: 7.3

### Description:
Using version ^7.0 for arcanedev/localization
./composer.json has been updated
Running composer update arcanedev/localization
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - arcanedev/localization[7.0.0, ..., v7.x-dev] require arcanedev/support ^7.0 -> satisfiable by arcanedev/support[7.0.0, 7.1.0, 7.1.1, 7.1.2].
    - arcanedev/support[7.0.0, ..., 7.1.2] require illuminate/filesystem ^7.0 -> found illuminate/filesystem[v7.0.0, ..., 7.x-dev] but it conflicts with another require.
    - Root composer.json requires arcanedev/localization ^7.0 -> satisfiable by arcanedev/localization[7.0.0, v7.x-dev].

### Steps To Reproduce:
- install new laravel 8 app and then
- composer require arcanedev/localization

**Comment by arcanedev-maroc** [comment]
Try again
