### ISSUE TITLE
How to get it working with Expose?

### ISSUE THREAD

**Issue by jartaud** [ARCANEDEV/Localization#161]
- Localization Version: 8.33.1
- Laravel Version: ^8.0
- PHP Version: 8.0.3

### Description:
I have installed this open source ngrok alternative https://github.com/beyondcode/expose and when I run the provided command, the app gets redirected to /home

I got it working using these tricks: https://github.com/beyondcode/expose/issues/24#issuecomment-805396556 but I've lost the localization.
```
// .env
PROXIES=127.0.0.1

// config/trustedproxy.php
'proxies' => env('PROXIES', null)

expose
or
expose share https://my-app.test

```

### Steps To Reproduce:

1. Install https://github.com/beyondcode/expose
2. cd into your laravel app
3. run expose or expose share https://your-app.test

**Comment by arcanedev-maroc** [comment]
Sorry but i can't assist you with this one because i've never used expose

**Comment by jartaud** [comment]
Thanks! 

I just move my home route outside of `Route::localizedGroup(function () {});` when I want to use expose. You can close the issue.
