### ISSUE TITLE
Use with cviebrock/eloquent-sluggable

### ISSUE THREAD

**Issue by swimlappy** [ARCANEDEV/Localization#17]
Hello,
I'm having some trouble using this package with https://github.com/cviebrock/eloquent-sluggable.  If I turn on slugged URLs with localization, I get a NotFoundHttpException visiting that slugged URL.  If I turn off the localization, slugged URLs works fine.

Has anyone successfully done slugging with this localization package?  What were you doing?

Thanks

**Comment by arcanedev-maroc** [comment]
Hi @swimlappy,

Honestly, i've never used the `cviebrock/eloquent-sluggable` package, so i've no idea what's your issue.
Can you provide us some code / config / example for test purposes to replicate your issue.

**Comment by swimlappy** [comment]
Sure.  Both packages work fine by themselves using the defaults.  There isn't much to the app yet though.

```
# config/sluggable.php
return [
    'build_from' => null,
    'save_to' => 'slug',
    'max_length' => 245,
    'method' => null,
    'separator' => '-',
    'unique' => true,
    'include_trashed' => false,
    'on_update' => true,
    'reserved' => null,
];

# config/localization.php
return [
    'supported-locales'      => ['en', 'pt-BR'],
    'accept-language-header' => true,
    'hide-default-in-url'    => false,
    'facade'                 => 'Localization',
    'route'                  => [
        'middleware' => [
            'localization-session-redirect' => true,
            'localization-cookie-redirect'  => false,
            'localization-redirect'         => true,
            'localized-routes'              => true,
        ],
    ],
    'locales'   => [
        'en'         => [
            'name'   => 'English',
            'script' => 'Latn',
            'dir'    => 'ltr',
            'native' => 'English',
        ],
        'pt-BR'      => [
            'name'   => 'Brazilian Portuguese',
            'script' => 'Latn',
            'dir'    => 'ltr',
            'native' => 'Português do Brasil',
        ],
    ],
];

# config/app.php
    'providers' => [
        ...
        Cviebrock\EloquentSluggable\SluggableServiceProvider::class,
        Arcanedev\Localization\LocalizationServiceProvider::class
    ],

# app/Http/routes.php
Route::group(['prefix' => Localization::setLocale(), 'middleware' => ['localization-session-redirect', 'localization-redirect']], function() {
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\AuthController@getLogin']);
    Route::post('login', ['as' => 'login_post', 'uses' => 'Auth\AuthController@postLogin']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\AuthController@getLogout']);

    Route::group(['middleware' => 'auth'], function () {
        Route::get('/', ['as' => 'main', 'uses' => 'MainController@index']);
        Route::resource('users', 'UserController');
    });

});

# simple user model
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('slug');
            $table->string('email')->unique();
            $table->string('password', 60);
            $table->rememberToken();
            $table->timestamps();
        });

# app/User.php
namespace app;
use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract,
                                    SluggableInterface
{
    use Authenticatable, Authorizable, CanResetPassword, SluggableTrait;

    protected $table = 'users';

    protected $fillable = [
        'name',
        'slug',
        'email',
        'password'
    ];

    protected $hidden = [
        'password',
        'remember_token'
    ];

    protected $sluggable = [
        'build_from' => 'name'
    ];
...

# bootstrap/app.php
...
$app->singleton(
    Illuminate\Contracts\Debug\ExceptionHandler::class,
    app\Exceptions\Handler::class
);

$app->singleton(
    'router',
    Cviebrock\EloquentSluggable\SluggableRouter::class
);
...
```

In this setup, I can visit `/en/users/1` or `/pt-BR/users/1` and localization works.  If I try and visit `/en/users/my-test-user` or `/pt-BR/users/my-test-user`, then I get a `NotFoundHttpException` exception thrown.  If I comment out the `Arcanedev\Localization\LocalizationServiceProvider::class` service provider, and fix my routes, then slugging works fine visiting `/users/my-test-user`.

I'm willing to try another slug package if one exists and is known to work.

Thank you for the help.
Jay

**Comment by arcanedev-maroc** [comment]
You're welcome Jay,

You can try this for the time being: 

Update your `routes.php` from:

``` php
Route::group(['prefix' => Localization::setLocale(), 'middleware' => ['localization-session-redirect', 'localization-redirect']], function() {
    //...
});
```

To :

``` php
Route::localizedGroup(function () {
    //...
});
```

It's more cleaner and based on your `localization.php` config file.

Check also the installation steps and especially this: https://github.com/ARCANEDEV/Localization/wiki/2.-Installation-and-Setup#now-you-need-to-update-your-http-kernel-to-use-the-localization-router 

And i'm afraid that i've found a conflict between the two packages :

``` php
$app->singleton(
    'router',
    Cviebrock\EloquentSluggable\SluggableRouter::class
);
```

with the Localization router: https://github.com/ARCANEDEV/Localization/blob/master/src/Providers/RoutingServiceProvider.php#L53

Did you know what the `Cviebrock\EloquentSluggable\SluggableRouter::class` do ??

Try to comment this `SluggableRouter` and see if it's fix your issue.

I'm gonna test your case when i've got free time, stay tuned :+1: .

_PS: Thanks for using my package._

Youness

**Comment by swimlappy** [comment]
My `app/Http/kernel.php` file did have the proper use statement, left it out of my previous post.  Sorry about that.  I've updated my `routes.php` file with the cleaner group, thank you for that.  The `Cviebrock\EloquentSluggable\SluggableRouter::class` allows me to use route model binding and route resource with the slug URL.  I suppose I could explicitly define my routes, but for this table just seemed faster not to do that.  The package doesn't appear to work unless I define that.

Jay

**Comment by arcanedev-maroc** [comment]
Ok i see.

You can try this, go to your `app/Providers/RouteServiceProvider.php` and add this inside the `boot()` method:

``` php
// app/Providers/RouteServiceProvider.php
//...
    public function boot(Router $router)
    {
        parent::boot($router);

        $router->model('user', 'App\User', function() {
            if (is_null($value)) {
                return null;
            }

            $model = new $class;

            $model =$model instanceof SluggableInterface 
                ? $model->findBySlugOrId($value)
                : $model->find($value);

            if (!is_null($model)) {
                return $model;
            }

            if ($callback instanceof Closure) {
                return call_user_func($callback, $value);
            }

            throw new NotFoundHttpException;
        });
    }
// ...
```

Now you can completely remove the :

``` php
$app->singleton(
    'router',
    Cviebrock\EloquentSluggable\SluggableRouter::class
);
```

**i've just copied the content out of it** :laughing: .

For more details, check the docs : http://laravel.com/docs/5.1/routing#route-model-binding

Check also the namespace of the `User` model class, it's `App` with capital **A** not `app`.

**Comment by swimlappy** [comment]
Tinkering with it to get this working.  Would I need to do this for every model I want to do route model binding with?  Seems like a lot of code to add, when I could normally accomplish it with just 1 line.

**Comment by arcanedev-maroc** [comment]
Nope, this is only to test and solve your issue, this is how it's gonna be (Something like that) :

``` php
// app/Providers/RouteServiceProvider.php
//...
    public function boot(Router $router)
    {
        parent::boot($router);

        $this->bindModel($router, 'user', 'App\User');
    }

    protected function bindModel(Router $router, $key, $class, Closure $callback = null) 
    {
        $router->model($key, function ($value) use ($class, $callback) {
            if (is_null($value)) {
                return null;
            }

            $model = new $class;

            $model =$model instanceof SluggableInterface 
                ? $model->findBySlugOrId($value)
                : $model->find($value);

            if (!is_null($model)) {
                return $model;
            }

            if ($callback instanceof Closure) {
                return call_user_func($callback, $value);
            }

            throw new NotFoundHttpException;
        });
    }
// ...
```

**Important:** 
- If the `$router->model()` is not working properly try `$router->bind()`, check [SluggableRouter](https://github.com/cviebrock/eloquent-sluggable/blob/master/src/SluggableRouter.php#L25).
- I have not test it in a laravel application, i've probably miss a semicolon or something :smile: .

**Comment by swimlappy** [comment]
Fair enough, I can test for sure. Implementing this at least I don't get any errors :-)  But I don't get any data from my model either.  Just blank when I visit the slug URL. Hmm

**Comment by arcanedev-maroc** [comment]
As i've said before, i've never used the `cviebrock/eloquent-sluggable` package, so i'm probably missing something.

But we are close to fix your issue ( ^_^)b

**Comment by swimlappy** [comment]
I understand.  I think we are close too.

**Comment by swimlappy** [comment]
Well, some good news. Looks like that worked.  I had to add a use statement at the top of my `RouteServiceProvider.php` file for `use Cviebrock\EloquentSluggable\SluggableInterface;` so that this check would pass

```
  $model = $model instanceof SluggableInterface
      ? $model->findBySlugOrId($value)
      : $model->find($value);
```

It was returning NULL and thus no data. Thank you for the help!  Perhaps this will help someone else looking to do the same thing.

Jay

**Comment by arcanedev-maroc** [comment]
Nice :+1:
