### ISSUE TITLE
transPost Bug

### ISSUE THREAD

**Issue by ndberg** [ARCANEDEV/Localization#20]
Hi 

It looks like there is a bug in transPost:

I have a form:

``` php
<form method="POST" action="/firma/profile/{{ $firma->id }}">
```

`resources/lang/de/routes.php`:

``` php
'firma-profile-id' => 'firma/profile/{id}',
```

And in my `/http/routes.php`:

``` php
Route::transGet('routes.firma-profile-id',  'FirmaController@profile');
Route::transPost('routes.firma-profile-id', 'FirmaController@update');
```

What happens: 
- it does not call the `FirmaController@update` method **->but it should**
- it does call the `FirmaController@profile` method **->but it shouldn't**

**EDIT :**
The `FirmaController@profile` is called from the `transPost` and not from the `transGet`. If I take out the `transPost` Line, the `transGet` rightly does not get called..

**Comment by arcanedev-maroc** [comment]
You need to specify a locale in your form `action` url.

Like this:

``` php
<form method="POST" action="/{{current-locale-here}}/firma/profile/{{ $firma->id }}">
```

**Comment by ndberg** [comment]
Thanks

**Comment by arcanedev-maroc** [comment]
Hi @JimLfe, why didn't use the `route()` method like this ?

``` php
// app/Http/routes.php

Route::transGet('routes.firma-profile-id',  [
    'as'   => 'firma.profile',
    'uses' => 'FirmaController@profile',
]);
Route::transPost('routes.firma-profile-id', [
    'as'   => 'firma.update',
    'uses' => 'FirmaController@update',
]);
```

``` php
<form method="POST" action="{{ route('firma.update', [$firma->id]) }}">
```

It's more clean and efficient like this.

**Comment by ndberg** [comment]
Hm Yes, thats a good idea... Didn't think about that.
