### ISSUE TITLE
Laravel 5.2 support

### ISSUE THREAD

**Issue by ndberg** [ARCANEDEV/Localization#22]
I've tested if the package already works with Laravel 5.2, unfortunatelly it's not. I get the exception:

> ErrorException in RouteTranslator.php line 165: Object of class Illuminate\Routing\UrlGenerator could not be converted to string

**Comment by mkwsra** [comment]
@arcanedev-maroc Please, upgrade this package to meet 5.2 :sweat_smile: 
:+1: Thansk jim for testing and pointing this out, I'm going to use it within couple days :yum:

**Comment by ndberg** [comment]
See also https://github.com/mcamara/laravel-localization/issues/272

**Comment by arcanedev-maroc** [comment]
@JimLfe @mkwsra

I'm working on it (See PR #23) :+1:

**Comment by arcanedev-maroc** [comment]
Done, the **Localization** package support **Laravel 5.2**.

Update the `arcanedev/localization` version to `>= 0.7`.

**Comment by mkwsra** [comment]
@arcanedev-maroc  you are super :heart_eyes:

**Comment by arcanedev-maroc** [comment]
You're welcome :satisfied:

**Comment by m7ammad7assan** [comment]
it is don't save local in session
