### ISSUE TITLE
Issue with middlewares under Laravel 5.2

### ISSUE THREAD

**Issue by luckyp70** [ARCANEDEV/Localization#24]
The provided Router class does not preserve middleware groups as defined in Kernel.php.
For instance, following middleware group definitions are simply ignored:

```
protected $middlewareGroups = [
    'web' => [
        \App\Http\Middleware\EncryptCookies::class,
        \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        \App\Http\Middleware\VerifyCsrfToken::class,
    ],

    'api' => [
        'throttle:60,1',
    ],
];
```

resulting in web or api class not found error while processing routes that include such middleware groups.

It seems that the approach to extend default Router needs to be reviewed in Laravel 5.2 (http://blog.lanin.me/extending-default-laravel-router/).

Please, make sure to update default Router extension according to Laravel 5.2 design.
Thank you.

**Comment by arcanedev-maroc** [comment]
Thanks @luckyp70, i'm going to check this.

BTW, feel free to make a pull request if you solved it.

**Comment by arcanedev-maroc** [comment]
Fixed, thanks for your feedback. :+1:
