### ISSUE TITLE
Language switcher and parameter translation.

### ISSUE THREAD

**Issue by jartaud** [ARCANEDEV/Localization#27]
Hello,
Say I have http://local.dev/category-slug, when i switch the language, I have http://local.dev/fr/category-slug. How can I grab the correct category translation from the DB so when i change the language, I can get something like http://local.dev/fr/categorie-slug or http://local.dev/es/categoria-slug?

``` php
// routes.php
Route::get('{category_slug}/{per_page}?', []);
```

**Comment by arcanedev-maroc** [comment]
Hi @jartaud, thanks for using this package.

BTW good question, did you checked [this section about the events](https://github.com/ARCANEDEV/Localization/blob/master/_docs/4-Usage.md#events) ?

**Comment by jartaud** [comment]
@arcanedev-maroc, thanks for your help.
Yeah i was playing with it, but i'm not quite sure i understand this part:

``` php
// You can store these translation in you database
$translations = [
    'view'  => [
        'en'    => [
            'slug'  => 'hello',
        ],
        'es'    => [
            'slug'  => 'hola',
        ],
        'fr'    => [
            'slug'  => 'salut',
        ],
    ],
];
// model: id, name, slug,  lang
```

How to transform this into `eloquent->toArray()` ?
Will i still have to use `Route::transGet()` ?

**Comment by arcanedev-maroc** [comment]
You're welcome @jartaud,

In your case, you need to replace this dummy code:

``` php
$translations = [
    'view'  => [
        'en'    => [
            'slug'  => 'hello',
        ],
        'es'    => [
            'slug'  => 'hola',
        ],
        'fr'    => [
            'slug'  => 'salut',
        ],
    ],
];

// This is just a dummy thing to fetch and merge the translation.
if (
    isset($translations[$route]) && isset($translations[$route][$locale])
) {
    $attributes = array_merge($attributes, $translations[$route][$locale]);
}
```

By using a custom helper or directly by using an eloquent model.

As you can see, the event listener gives you three arguments (`$locale`,`$route` & `$attributes`).

So you can do something like this:

``` php
Event::listen('routes.translation', function ($locale, $route, $attributes) {
    switch ($route) {
        case 'route-name-for-categories':
            $attributes = YourEloquentModel::customTranslateMethod($locale, $attributes);
            break;

        case 'another-route-name':
            $attributes = CustomHelper::translateMethod($locale, $attributes);
            break;

        //...

        default:
            // Do nothing if does not match any route
            // no break
    }

    return $attributes;
});
```

**The main goal is to translate the `$attributes` argument.**

And YES, you need to use the `Route::transGet()` for the translated routes.

**Comment by jartaud** [comment]
What's the route name in this piece of code ?? 

Do you have any real example combining the switcher with routes.translation event ?

``` php
Event::listen('routes.translation', function ($locale, $route, $attributes) {
    // You can store these translation in you database
    // or using the laravel's localization folders
    $translations = [
        'view'  => [
            'en'    => [
                'slug'  => 'hello',
            ],
            'es'    => [
                'slug'  => 'hola',
            ],
            'fr'    => [
                'slug'  => 'salut',
            ],
        ],
    ];

    // This is just a dummy thing to fetch and merge the translation.
    if (
        isset($translations[$route]) && isset($translations[$route][$locale])
    ) {
        $attributes = array_merge($attributes, $translations[$route][$locale]);
    }

    return $attributes;
});
```

**Comment by arcanedev-maroc** [comment]
This is a full example how to use it:

``` php
// routes.php
Route::localizedGroup(function () {
    // Other routes ...

    Route::transGet('routes.view', [
        'as'   => 'view-route',
        'uses' => function ($slug) {
            return 'The slug has been translated : ' . $slug;
        },
    ]) ;
});
```

Localization:

``` php
// resources/lang/en/routes.php
<?php

return [
    'view'  => 'view/{slug}'
];

// resources/lang/es/routes.php
<?php

return [
    'view'  => 'ver/{slug}'
];

// resources/lang/fr/routes.php
<?php

return [
    'view'  => 'afficher/{slug}',
];
```

And register the event listener:

``` php
Event::listen('routes.translation', function ($locale, $route, $attributes) {
    // You can store these translation in you database
    // or using the laravel's localization folders
    $translations = [
        'view-route'  => [
            'en'    => [
                'slug'  => 'hello',
            ],
            'es'    => [
                'slug'  => 'hola',
            ],
            'fr'    => [
                'slug'  => 'salut',
            ],
        ],
    ];

    // This is just a dummy thing to fetch and merge the translation.
    if (
        isset($translations[$route]) && isset($translations[$route][$locale])
    ) {
        $attributes = array_merge($attributes, $translations[$route][$locale]);
    }

    return $attributes;
});
```

And also make sure that **localized-routes** and **translation-redirect** are enabled.

And if you're not sure what is the current route in the event listener, you just `dd($route)` to see what is your route name of a specific url.

If you want to understand how its done behind scene, check [TranslationRedirect Middleware](https://github.com/ARCANEDEV/Localization/blob/master/src/Middleware/TranslationRedirect.php).

**Comment by jartaud** [comment]
Thank you so much dude!

**Comment by arcanedev-maroc** [comment]
You're welcome :+1:

**Comment by jartaud** [comment]
In order to use event translation with Eloquent, I use an Artisan Command to create an array of translations: https://gist.github.com/jartaud/195d050304892df51542

What do you think?

**Comment by arcanedev-maroc** [comment]
Great work @jartaud, but it's a little bit complicated in my opinion.

Don't do the same thing what i've done in the event listener, my example is just a dummy code for demonstration.

I'm sure you can do better than this (without artisan command), try to create a custom Helper like `ModelTranslator` to translate your models dynamically instead of generating a file (you can also use the caching system).

You are free to do whatever is good for your project, just be more creative & keep it simple.

I going to close this because the issue/question was solved.

But feel free to create a new issue or a PR to contribute to this package.

**Comment by arcanedev-maroc** [comment]
I going to close this because the issue/question was solved.

But feel free to create a new issue or a PR to contribute to this package.

**Comment by jartaud** [comment]
Thanks again. I've been fooled by a slow homestead on Windows. Yeah i'll refactor 

Great package :100:

**Comment by jasperjorna** [comment]
How can we have the correct URL already show up inside the navbar language switcher?

Translating slugs with the Event::listen method works when actually hitting the URL, as it then redirects to the correct one. But the alternative URL's initially show up in the current language in the language switcher. `vrachtwagens` is the variable slug in this example.

```html
<ul class="nav navbar-nav navbar-right">
  <li>
    <a href="http://local.dev/stock/vrachtwagens" rel="alternate" hreflang="en">
      English
    </a>
  </li>
  <li class="active">
    <a href="http://local.dev/nl/aanbod/vrachtwagens" rel="alternate" hreflang="nl">
      Nederlands
    </a>
  </li>
</ul>
```
The URL for English however should be pointing to `http://local.dev/stock/trucks`.
When clicking on it, it does redirect to that URL.
