### ISSUE TITLE
Localization facade not found

### ISSUE THREAD

**Issue by vuongdinhngoc** [ARCANEDEV/Localization#28]
It hasn't done automatically. I need to register it in config/app.php and it works fine.
P/S: I am using Laravel 5.2

**Comment by arcanedev-maroc** [comment]
OK thanks, i'm going to check this tomorrow.

**Comment by arcanedev-maroc** [comment]
You're right, the facade wasn't registered auto-magically.

I fixed this issue. Thanks again :+1: 

**Bonus:** You can registered it manually if you want. Or using the `localization()` helper.
