### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by ghost** [ARCANEDEV/Localization#34]
hello, i dont understand this can anyone help me

this is my routes file

``` php
<?php

Route::localizedGroup(function () {

    Route::group(['middleware' => 'web'], function () {

        Route::get('/', 'Frontend\HomeController@home')->name('frontend.index');

        Route::get('login', 'Auth\AuthController@getLogin');

    });

});
```

so when i change my language to NL or TR it works fine in homepage, but when i click to **/login** it redirects me to the default locale **/en/login**
so how do i make sure it stays to the selected language ?

**Comment by arcanedev-maroc** [comment]
Try to change the order and see if it's gonna resolve your issue:

``` php
Route::group(['middleware' => 'web'], function () {
    Route::localizedGroup(function () {
        Route::get('/', 'Frontend\HomeController@home')->name('frontend.index');

        Route::get('login', 'Auth\AuthController@getLogin');
    });
});
```

**Comment by ghost** [comment]
Thanks it works :)

**Comment by ghost** [comment]
hmm now i cant login when i try to login it refresh the page instead

**Comment by arcanedev-maroc** [comment]
Did you defined the post route for login ?

**Comment by ghost** [comment]
yes i have working admin panel but when i use `Route::localizedGroup` i cant login to my dashboard.

**Comment by arcanedev-maroc** [comment]
What is the real issue ? you can't post the credentials ? did you get any errors ?

Do you need a localized admin panel ? Try to put all the auth & admin routes outside the `Route::localizedGroup()`.

Please give more details to identify the issue.

**Comment by ghost** [comment]
Well when i try to login to my site its just redirecting back to the login page without any errors.

**Comment by arcanedev-maroc** [comment]
The page doesn't refresh, it's a 302 redirection when you hit submit (caused by `redirect()->back()` i think).

**EDIT :**
Can you debug this and see what happen : https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php#L57-L86

Try to check if the `Route::localizedGroup()` affects all the post forms or only the login form.

**Comment by ghost** [comment]
I have put all the auth routes outside the `Route::localizedGroup()` now its working.

**Comment by arcanedev-maroc** [comment]
Glad that you've solved your issue, i'm going to clean this discussion to keep your work "private".

Thanks for using the package :+1:

**Comment by ghost** [comment]
Thank you for making our development easier.
