### ISSUE TITLE
Access level to Arcanedev\Localization\LocalizationServiceProvider::publishConfig() must be protected

### ISSUE THREAD

**Issue by vince749** [ARCANEDEV/Localization#37]
Hi,

When i "composer update" :
[...]
- Removing arcanedev/support (3.7.5)
- Installing arcanedev/support (3.8.0)
  [...]

I have this error : 
[...]
PHP Fatal error:  Access level to Arcanedev\Localization\LocalizationServiceProvider::publishConfig() must be protected (as in class Arcanedev\Support\PackageServiceProvider) or weaker in /Users/vince/Sites/projects/dujour/menu/vendor/arcanedev/localization/src/LocalizationServiceProvider.php on line 11

Thanks

**Comment by vince749** [comment]
Ok, i waiting for updating package ;-)  

with this : https://github.com/ARCANEDEV/Localization/pull/36

**Comment by arcanedev-maroc** [comment]
Sorry about that @vince749
Fixed: #38

**Comment by arcanedev-maroc** [comment]
Hi @vince749, try to update your localization package to `0.7.5` and see if it solves your issue.

**Comment by vince749** [comment]
@arcanedev-maroc Yes! It's perfect ! Thanks

**Comment by arcanedev-maroc** [comment]
You're welcome :+1:
