### ISSUE TITLE
Route::auth() validation issue!!!

### ISSUE THREAD

**Issue by aketai** [ARCANEDEV/Localization#39]
Validation not work in localizedGroup: 

``` php
Route::localizedGroup(function () {
    // ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP

    Route::auth();
});
```

Please help to fix this issue!
Laravel Framework version 5.2.30
php artisan make:auth
Thank you

**Comment by arcanedev-maroc** [comment]
Can you give us more details about your issue ?

Check also this closed issue: #34

**Comment by aketai** [comment]
Very simple step by step:
1) Fresh installation laravel version 5.2.30
2) php artisan make:auth
3) "arcanedev/localization": "0.7.*" - composer update etc...
all works perfect 

But auth validation not working  if i place `Route::auth();` in 

``` php
Route::localizedGroup(function () {
    // ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP
    Route::auth(); 
    Route::get('/', 'HomeController@index');
});
```

If place `Route::auth();` outside of `localizedGroup` - validation is work!

Please help

**Comment by aketai** [comment]
Hi arcanadev,

Any news regarding my issue?

**Comment by arcanedev-maroc** [comment]
Hi @aketai,

Sorry but i need some time to test it in a laravel project and debug it.

For the time being, you can extract the `Route::auth()` outside of `Route::localizedGroup()` if it's urgent.

**Comment by ghost** [comment]
came across this today. quite easy to get around actually, you just need to manually define your auth routes rather than using the helper and then update the auth views.

``` php
Route::transGet('routes.login', [
    'as'   => 'login',
    'uses' => 'Auth\AuthController@showLoginForm',
]);
Route::transPost('routes.login', [
    'as'   => 'login',
    'uses' =>  'Auth\AuthController@login',
]);

// etc...
```

Then in your auth view you can do something like

``` blade
<form role="form" method="POST" action="{{ route('login') }}">
```

**Comment by arcanedev-maroc** [comment]
Yeah, this is what i do in all my projects (avoiding the `Route::auth()` method).

Thanks @digitalturtle for clarifying it.

**Comment by ghost** [comment]
@arcanedev-maroc can you give an example of what your routes setup looks like for the password reset auth routes? i'm having issues getting this to work with the /password/reset/{token?} route

**Comment by arcanedev-maroc** [comment]
The example for auth routes is here: #58
