### ISSUE TITLE
Undefined variable: supportedLocales

### ISSUE THREAD

**Issue by shanka12** [ARCANEDEV/Localization#40]
followed your configuration and used following code for menu

``` php
@foreach($supportedLocales as $key => $locale)
    <li class="{{ localization()->getCurrentLocale() == $key ? 'active' : '' }}">
        <a href="{{ localization()->getLocalizedURL($key) }}" rel="alternate" hreflang="{{ $key  }}">
            {{ $locale->native() }}
        </a>
    </li>
@endforeach
```

I am getting following error. anyone can help me to fix this? I want to display language switcher

`Undefined variable: supportedLocales`

**Comment by arcanedev-maroc** [comment]
Of course, you didn't pass the `$supportedLocales` variable to your custom navbar view.

Try to use `{{ Localization::localesNavbar() }}`.instead ([See this method](https://github.com/ARCANEDEV/Localization/blob/master/src/Localization.php#L401)).

**Comment by shanka12** [comment]
Thank you @arcanedev-maroc
