### ISSUE TITLE
Persistent Locale

### ISSUE THREAD

**Issue by Krato** [ARCANEDEV/Localization#44]
Hi, i just install this package. But I'm a little confused.

I have `config/app.php` with:

``` php
'locale' => 'es',
```

And `config/localization.php`as:

``` php
'supported-locales'      => ['en', 'es'],

    'accept-language-header' => true,

    'hide-default-in-url'    => false,

    'facade'                 => 'Localization',

    /* ------------------------------------------------------------------------------------------------
     |  Route
     | ------------------------------------------------------------------------------------------------
     */
    'route'                  => [
        'middleware' => [
            'localization-session-redirect' => true,
            'localization-cookie-redirect'  => false,
            'localization-redirect'         => true,
            'localized-routes'              => true,
            'translation-redirect'          => true,
        ],
    ],
```

I have and admin panel without routes translates. And In my views if I call `dump(\App::getLocale())`, allways get `en` never`es`. But `es` is the default language. If I call `dump(\App::getLocale())` in `routes.php` file shows `es`.

But If I call `Localization::getCurrentLocale()`shows correctly `es`.

My route is for example: `blog/new`. And Route is not in localization middleware:

``` php
Route::group(['prefix' => 'admin', 'middleware' => 'role:admin'], function() 
{
    Route::get('/blog/new', '\App\Blog\Controllers\PostController@create');
});
```

Why locale is set to `en`? How can I do it?

Thanks!

**Comment by arcanedev-maroc** [comment]
Honestly, i can't see what is exactly your issue (and i can't reproduce it).

But, if you want to force the locale (Single locale for the admin panel), set a default locale inside a constructor of your Base Admin Controller and extend it to your Controllers (Use the `Localization::setLocale()` method).

Or use the `Localization::getCurrentLocale()` instead of `App::getLocale()`.

**Comment by Krato** [comment]
Sure, I can use `Localization::getCurrentLocale()`. But the problem is that APP load lang files using `App::getLocale()`. So I need to fix it.
