### ISSUE TITLE
getLocalizedUrl returns only default lang url when artisan route:cache run

### ISSUE THREAD

**Issue by idubz33** [ARCANEDEV/Localization#45]
E.g. `\Localization::getLocalizedUrl('de', route('about'))` will produce an English (my app's default language) url instead of the proper `transRoute` url due to Laravel 5's route caching. If I `artisan route:clear` everything works as normal. A major dilemma is without route caching my app will run too slow for production, on the other hand with cache my app will run faster but the urls will be wrong. Is there any way to fix this?

**Comment by arcanedev-maroc** [comment]
I don't think it's going to work if you use the `route:cache`.

The routes are kinda dynamic for every locales (translated routes), if you want to cache the routes, you need to duplicate the routes for each locales.
