### ISSUE TITLE
[Question] - Locales config variables

### ISSUE THREAD

**Issue by paper9oll** [ARCANEDEV/Localization#46]
Hi Arcanedev,

Is it possible to forgo `locales` variables (`'script'` & `'dir'`) located in `config/localization.php`?

The reason i'm asking this is because my website uses Country-based routes instead of Language-based routes like `/us` instead of `/en`.

**Comment by arcanedev-maroc** [comment]
You can leave the `script` and `dir` empty.

You can also add a custom locale (`us`) inside the [locales](https://github.com/ARCANEDEV/Localization/blob/master/config/localization.php#L34) array.

**Comment by paper9oll** [comment]
@arcanedev-maroc Okay i tried but an error popup out below is the code i use

```
'us' => ['name' => 'United States', 'native' => 'United States', 'regional' => 'en_US']
```

It would work if i add in `'script'` and `'dir'` like below

```
'us' => ['name' => 'United States', 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'United States', 'regional' => 'en_US']
```

Hence i would like to know why i need to put `'script'` and `'dir'`?

**Comment by arcanedev-maroc** [comment]
Because the `script` and `dir` are [required](https://github.com/ARCANEDEV/Localization/blob/master/src/Entities/Locale.php#L82-L83) to create the Locale entity.

**Comment by paper9oll** [comment]
@arcanedev-maroc oh i see. thanks you
