### ISSUE TITLE
Extending a class Locale.php

### ISSUE THREAD

**Issue by seb-jean** [ARCANEDEV/Localization#49]
I need to extend your a class in your entities folder called Locale.php for add parameter config.

How do I go about doing that?

Thanks :)

I would like have

``` php
<?php

return [
    // ...

    'locales'   => [
        // A
        //====================================================>
        'aa'         => [
            'name'   => 'Afar',
            'script' => 'Latn',
            'dir'    => 'ltr',
            'native' => 'Qafar',
            'datepicker' => 'af'
        ],

        // ...

        'zu'         => [
            'name'   => 'Zulu',
            'script' => 'Latn',
            'dir'    => 'ltr',
            'native' => 'IsiZulu',
            'datepicker' => 'zu'
        ],
    ],
];
```

instead of 

``` php
<?php

return [
    // ...

    'locales'   => [
        // A
        //====================================================>
        'aa'         => [
            'name'   => 'Afar',
            'script' => 'Latn',
            'dir'    => 'ltr',
            'native' => 'Qafar',
        ],

        // ...

        'zu'         => [
            'name'   => 'Zulu',
            'script' => 'Latn',
            'dir'    => 'ltr',
            'native' => 'IsiZulu',
        ],
    ],
];`
```

**Comment by arcanedev-maroc** [comment]
Hi @sebastienjean76, thanks for using this package.

When you say extending the `Locale` Entity class, you mean removing a parameter like `regional` or adding new one ??

Can you give me an example to see what you want to achieve ?

**Comment by seb-jean** [comment]
Hello :)

I would like add new parameter.

It's for add locale datepicker for my project and so it's different according the language.

**Comment by arcanedev-maroc** [comment]
OK, i see what you want to achieve.

The fast/optimal solution for this is by using a config file like this (Single responsibility principle thing):

``` php
<?php 
// config/datepicker.php

return [
    'aa' => 'af',
    'zu' => 'zu',
];
```

And access it like this `config('datepicker.' . Localization::getLocale())`.

I'm going to think about it and find an eloquent way to extend the `Locale` entity.

**Comment by seb-jean** [comment]
Ok thanks. I try this way ;).

**Comment by seb-jean** [comment]
It's `config('datepicker.' . Localization::getCurrentLocale())` instead of `config('datepicker.' . Localization::getLocale())`

**Comment by arcanedev-maroc** [comment]
My bad :stuck_out_tongue_closed_eyes:
