### ISSUE TITLE
Translated routes redirect

### ISSUE THREAD

**Issue by JorgeAnzola** [ARCANEDEV/Localization#51]
I'm in a weird situation. I hope someone can help me.

Only the translated routes in es/routes.php gets redirected.

_//// productos means products in spanish_

**Behaviour:**
_// with locale == es_
project.dev/productos -> project.dev/es/productos
project.dev/products -> 404

_// with locale == en_
project.dev/productos -> project.dev/en/products
project.dev/products -> 404

**es/routes.php**
`return [
    'products' => 'productos'
];`

**en/routes.php**
`return [
    'products' => 'products'
];`

**routes file**
`Route::transGet('routes.products', 'PublicPagesController@showProducts');`

with middlewares

`'localization-session-redirect', 'localization-redirect'`

**Comment by arcanedev-maroc** [comment]
Can you also enable the middleware `localized-routes` and see if it's solves your issue ?

Check also [the documentation about the translated routes](https://github.com/ARCANEDEV/Localization/blob/master/_docs/4-Usage.md#translated-routes).

**Comment by JorgeAnzola** [comment]
Still nothing. My current 'locale' and 'fallback_locale' are both 'es' (in config/app.php). If I change it to 'en', the problem goes the other way, just en/routes.php gets redirected.

Also, I added 

`'locales' => [
        'es' => 'Spanish',
        'en' => 'English'
    ],` 
to the config/app.php file. And nothing.

Any ideas?

**Comment by arcanedev-maroc** [comment]
About the last change, instead of:

``` php
// config/app.php
'locales' => [ 'es' => 'Spanish', 'en' => 'English' ],
```

use your `localization.php` config file to set your [supported locales](https://github.com/ARCANEDEV/Localization/blob/master/config/localization.php#L8).

**Comment by JorgeAnzola** [comment]
Yeah, of course. That last change was just an addition. Just me trying to make it work.

In my localization.php file is
`'supported-locales'      => ['en', 'es'],`

**Comment by arcanedev-maroc** [comment]
OK, now i just need time to try your case with a new laravel installation, try to reproduce/debug your case and see what is the issue.

If you found the solution, please share it with us to help others.

**Comment by JorgeAnzola** [comment]
Yeah, of course, I'd continue trying things. Although I'm really starting at Laravel, I'm pretty noob. I've made a new repo, here is the code if it helps you. https://github.com/JorgeAnzola/another

(Sorry if my code is too messy or noobie. I'm practicing)

**Comment by filipveschool** [comment]
@JorgeAnzola why dont you use the `Route::localizedGroup()` ? Maybe this fixes it. Because I also use this package and when I go back to the previous page i have zero problems.

https://github.com/ARCANEDEV/Localization/blob/master/_docs/4-Usage.md
