### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by gitllermopalafox** [ARCANEDEV/Localization#55]
Hi,

Since your package is supporting from Laravel 5.0.x, could you consider to reduce the php version to >=5.4 in the composer.json requirements?

Thanks.

**Comment by arcanedev-maroc** [comment]
The reason for not supporting PHP 5.4 because it reached the "End of life", you can [check this page for more details](http://php.net/supported-versions.php).

Late this year, we are going to drop the PHP 5.5 version.
