### ISSUE TITLE
App::getLocale() is incorrect as is getCurrentLocale outside of Route::localizedGroup

### ISSUE THREAD

**Issue by moopa** [ARCANEDEV/Localization#60]
I found a similar issue here:
https://github.com/ARCANEDEV/Localization/issues/44

Even if I switch to `Localization::getCurrentLocale()` it always defaults to the default language of the site if the middleware is not used on some routes. This was a problem with the original https://github.com/mcamara/laravel-localization package which is why I tried yours.

To be clear, as long as the routes are setup with `localizedGroup` they work ok but any outside of this return the default site language. We have a custom language setup that really needs to use `App::getLocale()`. I'd really appreciate it if you could take a look.

Thanks

**Comment by arcanedev-maroc** [comment]
Hi @moopa, thanks for using this package 👍 .

When you say:

> To be clear, as long as the routes are setup with `localizedGroup` they work ok but any outside of this return the default site language.

I think this is the excepted behavior because it's in the localization scope.

For you custom setup, you can use `App::setLocale()` & `App::getLocale()` to manipulate your default language, and if you used session middleware for the localization you can retrieve the selected locale via a [session helper](https://github.com/ARCANEDEV/Localization/blob/master/src/Middleware/LocaleSessionRedirect.php#L32) to use it in your custom setup.

Regards,

**Comment by moopa** [comment]
Thanks for the reply. I have been playing around with the code.
It looks to me that `setLocale` is called everywhere and is set as null when not in `localizedGroup`
As an example, if I have routes outside of `localizedGroup` and I dump the $locale here it is null:

``` php
public function setLocale($locale = null)
{
    dd($locale);
    return $this->localesManager->setLocale($locale);
}
```

Even if I attempt to call this method myself with a locale, it is set as null. It would be really helpful if we could set the locale anywhere in the app and for it to set App locale also. Having to use and maintain 2 different methods is problematic.

**Comment by arcanedev-maroc** [comment]
> It looks to me that `setLocale` is called everywhere and is set as null when not in `localizedGroup`.

Laravel need to load all the routes, it will eventually run `Route::localizedGroup()` on every request. 

**Note:** This is Localization's `setLocale()` and not `App::setLocale()`.

And this is why `$locale` is null (when loading the routes) : https://github.com/ARCANEDEV/Localization/blob/master/src/Routing/Router.php#L61

Can you tell me what you want to achieve (a sample code is better) to understand your issue and reproduce it ?

**Comment by moopa** [comment]
Thanks for your continued quick responses.

Ok. Our website has a shop area that sits behind some additional order middleware. It has various ajax routes and also a third party payment page that requires us to send back links to our site (e.g. payment complete, payment failed urls. I was hoping to avoid localising any of the ordering routes to avoid potential issues. It is also entirely gated so SEO here is redundant.

Also, If the user changes their language via our current language selector, we update their order with the new language and change the `App::setLocale()` to reflect the new language. When the order is processed, we use queues / events and pull the language from the Order model to send confirmation emails etc. Finally, our language data does not rely on Laravels built in translations. It is edited in the db and output to a json file that we pull keys from based on `App::getLocale()`.

Ideally, I would like to use our current `LanguageController` and use `Localization::setLocale()` which in turn sets `App::setLocale()`.

I hope this makes sense. Our language selector code would ideally look a bit like this:

``` php
public function localise($locale)
{
    if(in_array($locale, ['en', 'fr', 'de'])) {

        localization()->setLocale($locale);

        // Set order language
        if($this->stores->orders()->hasOrder())
        {
            $this->stores->updateOrderDetails([
                'language'  => $locale
            ]);
        }
    }

    $url = \Localization::getNonLocalizedURL(\URL::previous());
    return redirect($url);
}
```

Thanks

**Comment by arcanedev-maroc** [comment]
OK, i don't know where to start but i'm going to give you a simple example to reproduce your app logic.

This is your locale selector:

``` php
Route::get('test', function () {
    echo '<a href="'.route('change-locale', ['en']).'">Click EN</a> <br>';
    echo '<a href="'.route('change-locale', ['es']).'">Click ES</a> <br>';
    echo '<a href="'.route('change-locale', ['fr']).'">Click FR</a> <br>';

    // This is for debbuging
    //------------------------------------------

    // Results before setting the locale
    echo "<pre>";
    var_dump(
        Session::get('selected_locale'),
        localization()->getCurrentLocale(),
        App::getLocale()                         
    );
    echo "</pre>";

    localization()->setLocale(Session::get('selected_locale')); // Change your app locale
    echo '<hr>';

    // Results after setting the locale
    echo "<pre>";
    var_dump(
        Session::get('selected_locale'),
        localization()->getCurrentLocale(),
        App::getLocale()
    );
    echo "</pre>";
});
```

And this is your `LanguageController` (Just an example): 

``` php
Route::get('change-locale/{locale}', [
    'as'   => 'change-locale',
    'uses' => function ($locale) {
        session('selected_locale', $locale);

        if (localization()->isLocaleSupported($locale)) {
            Session::put('selected_locale', $locale);
            // Your logic
        }

        return redirect(
            localization()->getNonLocalizedURL(\URL::previous())
        );
    }
]);
```

As you can see, i put the routes outside the `Route::localizedGroup()`, so you need to create your own localization system by using sessions.

Why using sessions ? because each request refresh your application configs to default, so you need to keep a trace by using session (or with URI, first segment is reserved for your locale and you can grab it in your app to change your config with a middleware and store it in your session).

You can try this example by visiting the `test` route and see how it's work.

**Bonus :** [Laravel - Request Lifecycle](https://laravel.com/docs/5.3/lifecycle)

**Comment by moopa** [comment]
I ended up just using the locale session var in a helper as you suggested when outside of the localizedGroup scope. I also put most of the site in the localizedgroup with the one exception of Socialite / Facebook where I had to use the helper methods to return to the correct page. Thanks for the support. Everything is working great.

**Comment by arcanedev-maroc** [comment]
You're welcome 👍
