### ISSUE TITLE
Localization disables POST requests

### ISSUE THREAD

**Issue by zangarmarsh** [ARCANEDEV/Localization#62]
I have a strange problem.
I placed my routes in the localization group but it disabled every POST request. I tried moving them out from the group and they actually work. Since I haven't read this problem so far in the internet, I'm asking here for help.

**Comment by arcanedev-maroc** [comment]
Can you check these issues : #39, #34, #61

Check also this: https://github.com/ARCANEDEV/Localization/issues/58#issuecomment-244463420
