### ISSUE TITLE
Set locale based on country?

### ISSUE THREAD

**Issue by thusfar7** [ARCANEDEV/Localization#63]
I use cloudflare. They provide visitor's country code.

What would be the best way to make sure that the visitor is set to locale that matches his country?

**Comment by arcanedev-maroc** [comment]
First of all you need to specify the supported locales for your application: https://github.com/ARCANEDEV/Localization/blob/master/config/localization.php#L8

You need to check if cloudflare provides compatible locales that are mentioned in `locales` (the locales codes are the keys): https://github.com/ARCANEDEV/Localization/blob/master/config/localization.php#L34-L2135

And the process is simple, you check the given locale is supported and if not, you set the default locale. You can do the check in a custom middleware.
