### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by ndberg** [ARCANEDEV/Localization#64]
Currently I have about 25 translated routes in my routes file. Since that, the performance got very worse. If I use route:cache the performance would be good, but then the translated routes would not work.

Perhaps it's something different, or does anybody of you guys have the same issue?

**Comment by arcanedev-maroc** [comment]
This feature (cached localized routes) doesn't exist yet because it's a little bit tricky.

Because it need to cache the translated routes with all supported locales.

For example: if you have 25 translated routes and 3 supported locales [EN, ES, FR], you're going to have 75 routes in your cache.

**Comment by ndberg** [comment]
Yes I know.. but do you have this performance troubles too?

**Comment by arcanedev-maroc** [comment]
I don't have a performance issue with this package. 

This is one of my multi language websites: http://red-tic.com/

You need to have a good server like a VPS with SSD.

Try also to optimize your app on production by running this commands:

``` bash
composer update --no-dev
composer dump-autoload -o
```
