### ISSUE TITLE
localization not saved between pages.

### ISSUE THREAD

**Issue by maorkavod** [ARCANEDEV/Localization#65]
Hi,

I am using your package for my Laravel application localization,
i follow each step in the docs, everything looks great except one issue :
when i redirect to my site like this :

www.mysite.com/fr

Im getting my site in FR like i expected. but when i click on some link inside the page, im getting back the the fallback lang, "en".
its not keeping the selected local between redirect of pages.
- my Laravel session cookie driver is : SESSION_DRIVER=file
- the session directory has permissions to writ the sessions file, they are created for each visit & login.
- i cleared the app cache and config files,

*the localization config is :

``` php
<?php

    'route' => [
        'middleware' => [
            'localization-session-redirect' => true,
            'localization-cookie-redirect'  => false,
            'localization-redirect'         => true,
            'localized-routes'              => true,
            'translation-redirect'          => true, 
        ],
    ], 
```
- my routs definition is like this : 

``` php

<?php
Route::group([
    'prefix'     => Localization::setLocale(),
    'middleware' => [
        'localization-session-redirect',
        'localization-redirect',
        'web'
    ],
], function () {
     //all my Routes that used the translation are in here....
});
```

how can i fix this? 
thanks!

**Comment by arcanedev-maroc** [comment]
Try this route group instead:

``` php
<?php

Route::group(['middleware' => 'web'], function () {
    Route::localizedGroup(function() {
        //...
    });
});
```

If you're using Laravel `5.2` or `5.3`, the `web` middleware is already included in [RouteServiceProvider](https://github.com/laravel/laravel/blob/master/app/Providers/RouteServiceProvider.php#L54-L59).

First, try to visit `www.mysite.com/fr`. After that, access the url without the locale `www.mysite.com`.

For the urls, try to use the `route()` method with named route.

**Comment by maorkavod** [comment]
i try that, still the same result, this is my current code : 

``` php
// app/Http/routes.php

Route::group(['middleware' => 'web'], function () {
    Route::localizedGroup(function() {

        Route::auth();
        Route::get('auth/logout', function(){
            Auth::logout();
            return redirect('/');
        });

        Route::get('', function () {
            if (Auth::check())
            {
                return view('home');
            }else {
                return view('welcome');
            }

        });


        //pages
        Route::get('/home', 'HomeController@index');
        //more Routes like the above.
    });
});
```

is this ok?

**Comment by arcanedev-maroc** [comment]
Is that laravel `5.2` ?

Try this example: https://github.com/ARCANEDEV/Localization/issues/58#issuecomment-244463420

**Comment by maorkavod** [comment]
I am using Laravel 5.3

from composer : 

"laravel/framework": "5.3.*",

**Comment by arcanedev-maroc** [comment]
Why your routes is in `app/Http/routes.php` ?

**Comment by maorkavod** [comment]
This is where it was when i download the Laravel framework before a year ago, 5.2
i did the upgrade to 5.3 before 2 months , works great no issues. 

you think that this cause the problem?
where this file should be located at?

**Comment by arcanedev-maroc** [comment]
This is the new routes file for web: https://github.com/laravel/laravel/blob/master/routes/web.php

Try to follow this upgrade guide: https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0

**Comment by maorkavod** [comment]
i didnt noticed this sesction :-\

i will give it a try and let you know with the result, thank you!

**Comment by maorkavod** [comment]
I finish this section upgrade,
my system is still working with all the routes like before.
the problem still exist. 

there is a flag in the package to make it work in debug mode?

**Comment by maorkavod** [comment]
``` php
Auth::routes();

Route::group(['middleware' => ['web']], function () {
    Route::group([
        'prefix'     => Localization::setLocale(),
        'middleware' => [
            'localization-session-redirect',
            'localization-redirect',
            'localized-routes',
        ],
    ], function() {

 });

    // Non Localized routes here
});
```

config :

``` php
'accept-language-header' => true,

'hide-default-in-url'    => false,

'facade'                 => 'Localization',

/* ------------------------------------------------------------------------------------------------
 |  Route
 | ------------------------------------------------------------------------------------------------
 */
'route'                  => [
    'middleware' => [
        'localization-session-redirect' => true,
        'localization-cookie-redirect'  => false,
        'localization-redirect'         => true,
        'localized-routes'              => true,
        'translation-redirect'          => true,
    ],
],
```
