### ISSUE TITLE
Laravel 5.3 Validation localized Massages - Shows Only default (en)

### ISSUE THREAD

**Issue by maorkavod** [ARCANEDEV/Localization#67]
Hi. 
i have Laravel 5.3 application with `ARCANEDEV/Localization` pack, work greate so far! :)
i have right now an issue with the validation massages. 

this is my Routes: 

```php
Route::group(['middleware' => ['web']], function () {
    Auth::routes();
    Route::group([
        'prefix'     => Localization::setLocale(),
        'middleware' => [
            'localization-session-redirect',
            'localization-redirect',
            'localized-routes'
        ],
    ], function() {

    // All Routes in here! 
    // Including some of the Auth GET methods (register & login page & reset password),
    // not the post routes.
    });
});
```

in the lang file i have this  (`/resources/lang/en/validation.php`): 

```php
'custom' => [
    'g-recaptcha-response' => [
        'captcha' => 'Are you a Robot?',
    ],
],
```

in the blade template i have this : 

```blade
<label class="input">
    {!! app('captcha')->display($attributes = [], $lang = Localization::getCurrentLocale()); !!}
    @if ($errors->has('g-recaptcha-response'))
	<span class="help-block">
	<strong>{{ $errors->first('g-recaptcha-response') }}</strong>
	</span>
    @endif
</label>
```

* the problem is that i have the translation for this captcha attribute, in more 2 languages.
no metter which  language i am, im getting the "en" text not the actual local of the current user.
all the other translation in the php code & the blade template are working fine, this issue is only regarding the validation errors. 

what could be the problem?

**Comment by arcanedev-maroc** [comment]
@maorkavod, are you getting all validation errors in `en` or only for the captcha ?

Which package you're using for captcha ?

You're not forgetting the translation of your captcha in other lang (instead of en) ? 

like `/resources/lang/fr/validation.php`:

``` php
'custom' => [
    'g-recaptcha-response' => [
        'captcha' => 'Etes-vous un Robot?',
    ],
],
```

**Comment by maorkavod** [comment]
No, i have this code in all the other languages, the same code block different text
its regarding all the errors massages, not just that one.
this was just for this example.

"arcanedev/localization": "0.8.*"

**Comment by arcanedev-maroc** [comment]
Can you put this code in your view and see what you get:

``` php
// Your form
<?php dump(app()->getLocale(), Localization::getCurrentLocale(), $errors); ?>
```

**Comment by maorkavod** [comment]
``` PHP
"he"
"he"

ViewErrorBag {#572 ▼
  #bags: array:1 [▼
    "default" => MessageBag {#571 ▼
      #messages: array:1 [▼
        "g-recaptcha-response" => array:1 [▼
          0 => "Are you a Robot?"
        ]
      ]
      #format: ":message"
    }
  ]
}
```

**Comment by arcanedev-maroc** [comment]
Can you show me your validator (with rules)?

**Comment by arcanedev-maroc** [comment]
@maorkavod Have you the translations `he` folder in your app ?

```
/resources/lang/he/auth.php
/resources/lang/he/pagination.php
/resources/lang/he/passwords.php
/resources/lang/he/validation.php
```

Check this repo: https://github.com/caouecs/Laravel-lang/tree/master/src/he

**Comment by maorkavod** [comment]
I Have made some changes bu still the same outcome, 

`/app/Http/Controllers/Auth/RegisterController.php`

``` php
protected function validator(array $data)
{
    return Validator::make($data, [
        'username' => 'required|max:255|unique:users',
        'email' => 'required|email|max:255',
        'password' => 'required|min:6|confirmed',
        'g-recaptcha-response' => 'required|captcha'
    ]);
}
```

regarding the translations folder, sure i have : 

![image](https://cloud.githubusercontent.com/assets/6458359/20137195/d00dbe30-a681-11e6-9afe-65fc802f7121.png)

**Comment by arcanedev-maroc** [comment]
OK, so you tell me that the only field that hasn't be translated is the captcha (g-recaptcha-response) field ?

The username, email, password fields are translated with no issue ?

Check the `/resources/lang/he/validation.php`:

``` php
'custom' => [
    'g-recaptcha-response' => [
        'captcha' => 'האם אתה רובוט?', // Google translate
    ],
],
```

**Comment by maorkavod** [comment]
regarding https://github.com/caouecs/Laravel-lang

awesome repo!!
thanks, save me a lot of time :)

to your question , no.. 
in all the rules of validation i m getting only the English, im guessing its because i set the fallback to "en".
if i writ different validation message for all the languages for some input , im getting only the English type.
no metter which language the site is.

**Comment by arcanedev-maroc** [comment]
The issue is caused by the translator inside the Validator class.

If you do this you're going to see the problem is:

``` php
protected function validator(array $data)
{
    $validator = Validator::make($data, [
        'username' => 'required|max:255|unique:users',
        'email' => 'required|email|max:255',
        'password' => 'required|min:6|confirmed',
        'g-recaptcha-response' => 'required|captcha'
    ]);

    dd(app()->getLocale(), $validator->getTranslator()->getLocale()); // they are going to be different locales

    return $validator;
}
```

**Comment by maorkavod** [comment]
i found out why, 
i have an issue with the Auth::routes(); and the Localization.
the issue was that  i had this code : 

``` PHP
Route::group(['middleware' => ['web']], function () {

    Route::group([
        'prefix'     => Localization::setLocale(),
        'middleware' => [
            'localization-session-redirect',
            'localization-redirect',
            'localized-routes'
        ],
    ], function() {
         //all my other pages .......
        //and this call :
        Auth::routes();
});
```

the problem was that the register post, and login post, didnt work, they return to the same page, and there was no error. so i think that maybe this because the  Auth routes post methods was inside the 
localization middleware, if i remove it from there the pages register & login was not localized. 
so my solution was like this , to keep all the "GET" Auth routes insdie your middleware, and keep the "POST" method out of there like this: 

``` PHP
Route::group(['middleware' => ['web']], function () {
    Auth::routes();
    Route::group([
        'prefix'     => Localization::setLocale(),
        'middleware' => [
            'localization-session-redirect',
            'localization-redirect',
            'localized-routes'
        ],
    ], function() {
         //all my other pages .....
         //Auth
        Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');

        // Registration Routes...
        Route::get('register', 'Auth\RegisterController@showRegistrationForm');

        // Password Reset Routes...
        Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
        Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');

});
```

so i think that in the post Routes, there is no localization middleware affrect, only the GET methods. 
do you know how this fix the post issue?

this will fix both issues at once.

**Comment by arcanedev-maroc** [comment]
This is a tested solution that i use for all my projects (last test was with laravel 5.2 and i think it will works with 5.3).

Check this: https://github.com/ARCANEDEV/Localization/issues/58#issuecomment-244463420

**Comment by maorkavod** [comment]
Im using Laravel 5.3 so i hade to change the controller path & name : 

``` PHP
 // Authentication Routes...
        Route::group(['prefix' => 'login', 'as' => 'login.'], function () {
            // auth::login.get
            Route::get('/',  ['as' => 'get',  'uses' => 'Auth\LoginController@showLoginForm']);
            // auth::login.post
            Route::post('/', ['as' => 'post', 'uses' => 'Auth\LoginController@login']);
        });


        // Registration Routes...
        Route::group(['prefix' => 'register', 'as' => 'register.'], function () {
            // auth::register.get
            Route::get('/',  ['as' => 'get',  'uses' => 'Auth\RegisterController@showRegistrationForm']);
            // auth::register.post
            Route::post('/', ['as' => 'post', 'uses' => 'Auth\RegisterController@register']);
        });

        // Password Reset Routes...
        Route::group(['prefix' => 'password', 'as' => 'password.'], function () {
            // auth::password.reset.get
            Route::get('reset/{token?}', ['as' => 'reset.get', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
            // auth::password.email
            Route::post('email',         ['as' => 'email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
            // auth::password.reset.post
            Route::post('reset',         ['as' => 'reset.post', 'uses' => 'Auth\ForgotPasswordController@reset']);
        });
```

still the GET method of register was worked fine and localized , but the POST method make a redirect the the previews page with no error anywhere.. 

i can fix this by passing the current local as input to the register post and reset in the validation function    the local, but i prefer to fix the problem it self.

**Comment by arcanedev-maroc** [comment]
You need to change also the form actions by using the `route()` helper like this:

``` blade
<form action="{{ route('auth::register.post') }}" method="POST">
```

This way you're gonna avoid the redirection because you're gonna specify the locale in your form's action with the route() helper instead of unlocalized url .

Check also the views in my comment.

**Comment by maorkavod** [comment]
Thank you very much! :+1: 
its working now!
