### ISSUE TITLE
Question against mcamara package

### ISSUE THREAD

**Issue by mtx-z** [ARCANEDEV/Localization#68]
Hey there !
I found your package from a macmara Github issue, so i would like to ask you few things to know if your package encounter the same problem that i have with Macmara's one (wich is still really great).

- I got the same problem as [here](https://github.com/mcamara/laravel-localization/issues/268), idk if it's due to model binding, but some URL works (language switcher correctly change the translated word in URL + code), some URL dont (language switcher just change the code in url, not translated word) all using getLocalizedURL()

**Comment by arcanedev-maroc** [comment]
When you say model binding, are you using model `id` or `slug` as a parameter ?

**Comment by mtx-z** [comment]
Hi, thanks for answering (that fast!).
I think it'll be easier with an example. 

Lets say i have 2 language: **FR** (french), and **EN** (english) wich is default.` Hide default language` is disabled, `AcceptHeaderLang `is enbaled (i'm still on Macmara's package). Default language is **EN**.

First, i got a static page content like (**WORKING**):
- `http://domain.com/en/myPageEn` for **EN**
- `http://domain.com/fr/myPageFr` for **FR**

> In this, the block "`myPage**`" is translated in route file (and have a translation value in translation file).
> Here the language switcher **works correctly/as expected**, so getLocalizedURL() works.

Now, another page, wich is reached by submitting a form [text search form] (**NOT WORKING**):
- `http://domain.com/en/searchEn/my+query` for **EN**
- `http://domain.com/fr/searchFr/my+query` for **FR**

> In this, the block "`search**`" is translated in route file (and have a translation value in translation file).
> Now, the language switcher (and so `getLocalizedURL()`) **dont work**. If in english, french URL (in switcher from `getLocalizedURL()`) will be:

- `http://domain.com/fr/searchEn/my+query (wich goes 404)` and not
- `http://domain.com/fr/searchFr/my+query` like it should be. 

Note that, when submitting the form from **EN** version or **FR** version, it works well and i get redirected to the correct URL. But the language switcher (and so `getLocalizedURL()`) on the result page is the problem.

Route is declared like so: 
`get(LaravelLocalization::transRoute('value.in.translation.file') . '/{query}', 'MyController@MyMethod')->name('name.of.the.route');`

All "problems" are from `getLocalizedURL()` wich is used for language switcher, alternate URL in `<head>` ... I dont understand why it works with one, and not with the other... 

If you need more infos, do not hesitate ! thanks again.

**Comment by arcanedev-maroc** [comment]
So the problem is when you use the language switcher with `getLocalizedURL()`, i'm right ?

And not while submitting the form (The best way to avoid the redirection while submitting the form is by using route names like this `action="{{ route('name.of.the.route') }}"`).

The remaining thing that i need to check is the language switcher with the usage of `getLocalizedURL()` (i think this is your main issue because you want to keep the navigation history while switching the language).

**Comment by mtx-z** [comment]
That is fully exact. 
All my problems are coming from `getLocalizedURL()` wich I use for language switcher and <head> alternate URLs. 
The form submit is not the problem, as as you said, i use `action="{{ route('name.of.the.route') }}"`, the controller then redirect user to the correct URL, depending its actual lang. 
But once on the result page, the language switcher (`getLocalizedURL()`) output wrong URLs, wich goes in 404 as url don't exist (edited my previous answer to say wich is going 404).

So yes, `getLocalizedURL()` is the problem here. I checked the method wich is a bit long/complex as parsing URL, checking parameters... Pretty complex method unfortunatly.. Of course, i would prefer the language switcher to work (and my `<head>` alternate urls), as if not, i'll have to disable alternate url in `<head>` and make the language switcher redirect to localized homepage but it's not really user friendly.

Thing is, it works with some page, and some not...

Thx a lot again

**Comment by arcanedev-maroc** [comment]
I think my package gonna works for you but you need to be aware how to tweak it.

Here is an [example](https://github.com/ARCANEDEV/Localization/blob/master/resources/views/navbar.blade.php#L2-L8) of using `getLocalizedURL()` method.

And you have two methods to achieve your goal:

```php
/**
 * Returns an URL adapted to $locale or current locale.
 *
 * @param  string|bool   $locale
 * @param  string|false  $url
 * @param  array         $attributes
 *
 * @return string|false
 */
public function getLocalizedURL($locale = null, $url = null, $attributes = [])

// OR

/**
 * Returns an URL adapted to $locale or current locale.
 *
 * @param  string       $url
 * @param  string|null  $locale
 *
 * @return string
 */
public function localizeURL($url = null, $locale = null);
```

And you can also use a special method like:

```php
/**
 * Returns an URL adapted to the route name and the locale given.
 *
 * @param  string|bool  $locale
 * @param  string       $transKey
 * @param  array        $attributes
 *
 * @return string|false
 */
public function getUrlFromRouteName($locale, $transKey, $attributes = [])
```

You can start using my package if you want. If you have questions or issues, feel free to post it in this repo.

I'll do my best to help you 👍

**Comment by mtx-z** [comment]
Thanks a lot !
So, in your package, you updated the Macmara getLocalizedURL() method ? Is your package from a Macmara's fork ?
Already using the ARCANEDEV logviewer, pretty cool :)

EDIT: just checked `withlocalizeURL()` from Macmara and result is the same. [This issue](https://github.com/mcamara/laravel-localization/issues/290) seems to be related, or exactly mine.

**Comment by arcanedev-maroc** [comment]
The package was based on Macmara's package (not a fork only similar logics and features) but i've rewritten/refactoring/testing/fixing a lot of code (+better code quality & code coverage).

[![scrutinizer-ci](https://img.shields.io/scrutinizer/g/ARCANEDEV/Localization.svg?style=flat-square)](https://scrutinizer-ci.com/g/ARCANEDEV/Localization/?branch=master) [![scrutinizer-ci](https://img.shields.io/scrutinizer/coverage/g/ARCANEDEV/Localization.svg?style=flat-square)](https://scrutinizer-ci.com/g/ARCANEDEV/Localization/?branch=master) 

The only thing that i can recommend is to start with a fresh laravel installation + ARCANEDEV/Localization package and see if it solves your issue and also to compare the differences with Macmara's Localization package.

Check the usage section about the [Translated routes](https://github.com/ARCANEDEV/Localization/blob/master/_docs/4-Usage.md#translated-routes), you're gonna see the difference (*eloquent way* to manage routes).

Check also this issue about the prefixed translations: https://github.com/ARCANEDEV/Localization/issues/10#issuecomment-149929259

**Comment by mtx-z** [comment]
The issue you linked seems to be like mine. The URL translation work on the first level, but when it need more it doesnt. 
I'll try your package on a clean project to see how it goes, and i keep you in touch :)

thx !

**Comment by mtx-z** [comment]
Just found out something with Macmara's package : 
- If i dont use any route::group with a localized prefix, it work. I mean, i have to put the **entire route path** in my route translation file.

Here is an example where language switcher **DONT WORK**: 

```php
Route::group(['prefix' => LaravelLocalization::transRoute('routes.announce-prefix')], function() {
    Route::get(LaravelLocalization::transRoute('routes.announce.create'), 'AnnounceController@create')
         ->name('frontend.announce.create');
});
```

```php
'announce-prefix' => 'announce-fr',
'announce'        => [
    'create' => 'create-fr',
],
```

Here is an example where language switcher **WORK**: 

```php
Route::get(LaravelLocalization::transRoute('routes.announce.create'), 'AnnounceController@create')
     ->name('frontend.announce.create');
```

```php
'announce-prefix' => 'announce-fr', //not used here anymore
'announce'        => [
    'create' => 'announce-fr/create-fr'
],
```

So, when i don't use any route prefix, and put the **entire route** in every language file, it works. WIth the prefix, the language switcher is not able to find the full translated URL. 

My 2days ago comment with issue on a text-search URL is now working, by putting the full URL string in every route language file.

**Comment by arcanedev-maroc** [comment]
Cool, glad you've fixed your issue.

I think this is what i've said in [my previous comment](https://github.com/ARCANEDEV/Localization/issues/10#issuecomment-149929259).

To organize the translations properly, try this (like REST 😉):

```php
'announce' => [
    'index'  => 'announce-fr',
    'create' => 'announce-fr/create-fr'
],
```

Bonne continuation 👍

**Comment by mtx-z** [comment]
Yep you're right ! 
One last thing (just for you to know), i just tested `getLocalizedURL()` and `getURLFromRouteNameTranslated()` with some `$attributes` _array_ in each.
My aim is to override for a particular page the language selector, as URL contain some DB stored slug value (slug is translated also). So i want to pass the right localized slug as attribute. But both method dont work, and the output don't care about the attribute array sent, parameter stay the same as actual URL. I need to `dump()` a bit more to see where it "breaks".

Anyway, it's just for you to know, hope your package will work better on all of this, will give it a try on my next project. 

Thanks again Arcanedev :)

**Comment by arcanedev-maroc** [comment]
You're welcome @mtx-z 👍 

You can translate even the attributes like `slug` with [localization's event](https://github.com/ARCANEDEV/Localization/blob/master/_docs/4-Usage.md#events).

Check this previous issue: https://github.com/ARCANEDEV/Localization/issues/27#issuecomment-171473588
