### ISSUE TITLE
View are translated on the second load

### ISSUE THREAD

**Issue by loranger** [ARCANEDEV/Localization#69]
Hello,

I (supposely) setup Localization as it should be, but I can't figure out why my view refuses to be translated on the first load.
When I click on the (out-of-the-box) navbar, my url change, my debug output in my `welcome.blade.php`

```php
{{ config('app.locale') }}
{{ \App::getLocale() }}
```

shows the correct language code, but my view does not change. I have to reload the page one in order to have the correctly translated page.

I can't understand what is my mistake ?
Do you have any clue ?

**Comment by arcanedev-maroc** [comment]
Hi,

When you say the views aren't translated on the first load, you mean that the `trans()` method doesn't work properly ?

Try to debug this:

```php
{{ config('app.locale') }}
{{ \App::getLocale() }}
{{ trans()->getLocale() }}
```

Also i need to see your setup (config, routes, views...) to reproduce your issue.

**Comment by loranger** [comment]
Hi,

Thanks for your reply.
I realize I didn't tell you, but I'm using Laravel 5.3.

Yes, that's exactly the problem :

With your debug, the last one is stuck on the previous language code.

In order to try to fix, I simplified my setup as I could, here it is

`config/app.php`
```php
...
Arcanedev\Localization\LocalizationServiceProvider::class,
...
```

My Kernel.php uses the Trait
```php
class Kernel extends HttpKernel {
    // Localization Trait
    use \Arcanedev\Localization\Traits\LocalizationKernelTrait;
...
```

My `config/localization.php` file is almost by default
```php
return [

    'supported-locales'      => ['en', 'fr', 'es', 'de', 'it', 'pt'],
    'accept-language-header' => true,
    'hide-default-in-url'    => false,
    'facade'                 => 'Localization',

    'route'                  => [
        'middleware' => [
            'localized-routes'              => true,
            'localization-redirect'         => true,
            'localization-session-redirect' => true,
            'localization-cookie-redirect'  => true,
            'translation-redirect'          => true,
        ],
    ],
...
```

And my routes (`routes/web.php`) are empty, in order to debug this issue

```php
<?php

Route::localizedGroup(function () {
    Route::get('/', function () {

        dump(config('app.locale'));
        dump(\App::getLocale());
        dump(trans()->getLocale());

        return trans('welcome.intro');
    });

});
```

And at least, here is the debug output for `http://my-project.local/` (redirecting to /fr because of my bowser's http-accept-language) :

```
"fr"
"fr"
"fr"
Bonjour et bienvenue !
```

Then I manually change the language code from my url address bar and try to switch to De 

```
"de"
"de"
"fr"
Bonjour et bienvenue !
```

**Comment by arcanedev-maroc** [comment]
Hi @loranger,

I just tested your setup with laravel 5.3 and it works for me.

Can you check that `Arcanedev\Localization\LocalizationServiceProvider::class` is between the service providers like this and see if it solves your issue:

```php
'providers' => [

    /*
     * Laravel Framework Service Providers...
     */
    Illuminate\Auth\AuthServiceProvider::class,
    Illuminate\Broadcasting\BroadcastServiceProvider::class,
    Illuminate\Bus\BusServiceProvider::class,
    Illuminate\Cache\CacheServiceProvider::class,
    Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
    Illuminate\Cookie\CookieServiceProvider::class,
    Illuminate\Database\DatabaseServiceProvider::class,
    Illuminate\Encryption\EncryptionServiceProvider::class,
    Illuminate\Filesystem\FilesystemServiceProvider::class,
    Illuminate\Foundation\Providers\FoundationServiceProvider::class,
    Illuminate\Hashing\HashServiceProvider::class,
    Illuminate\Mail\MailServiceProvider::class,
    Illuminate\Notifications\NotificationServiceProvider::class,
    Illuminate\Pagination\PaginationServiceProvider::class,
    Illuminate\Pipeline\PipelineServiceProvider::class,
    Illuminate\Queue\QueueServiceProvider::class,
    Illuminate\Redis\RedisServiceProvider::class,
    Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
    Illuminate\Session\SessionServiceProvider::class,
    Illuminate\Translation\TranslationServiceProvider::class,
    Illuminate\Validation\ValidationServiceProvider::class,
    Illuminate\View\ViewServiceProvider::class,

    /*
     * Package Service Providers...
     */
    Arcanedev\Localization\LocalizationServiceProvider::class,

    /*
     * Application Service Providers...
     */
    App\Providers\AppServiceProvider::class,
    // App\Providers\BroadcastServiceProvider::class,
    App\Providers\AuthServiceProvider::class,
    App\Providers\EventServiceProvider::class,
    App\Providers\RouteServiceProvider::class,

],
```

**Comment by loranger** [comment]
Thank you for your support.

Actually, I already tried with a brand new fresh Laravel 5.3 install and it worked perfectly for me, too.

While I was verifying the ServiceProvider position (which is already in the middle, between the Laravel service providers and the Application service providers), I also comment all the other Package service providers... And found the issue comes from a conflict with an other package I use: [vsch/laravel-translation-manager](https://github.com/vsch/laravel-translation-manager/).

I already used both for previous project, but it seems with Laravel 5.3, something is broken.
Unfortunately, I don't know if the break comes from Localization or laravel-translation-manager...

With your knowledge, could you please take a look at this conflict in order to understand where the issue reside ?

**Comment by arcanedev-maroc** [comment]
Can you try this workaround and see if it fix your issue:

```php
<?php

Route::localizedGroup(function () {
    // Sync the translator locale with the app locale
    trans()->setLocale(app()->getLocale());

    Route::get('/', function () {

        dump(config('app.locale'));
        dump(\App::getLocale());
        dump(trans()->getLocale());

        return trans('welcome.intro');
    });
});
```

**Comment by loranger** [comment]
I'm afraid the result is the same 😞 

Did you try to install the other package within the fresh Laravel 5.3 test you had ?

**Comment by arcanedev-maroc** [comment]
I tested the other package and i think it broke the translation logic.

See this: https://github.com/vsch/laravel-translation-manager/issues/55

So the solution is to add `'use_cookies' => false,` in your `laravel-translation-manager.php` config file and see if it solves your issue.

PS: Tu me dois un café.

**Comment by loranger** [comment]
It definitely works !

Thank you so much for your support, I would have create the issue if you told me, thanks for this, too.

PS : Avec plaisir ;)
