### ISSUE TITLE
Resource routes not working when the package is active

### ISSUE THREAD

**Issue by hamzstramgram** [ARCANEDEV/Localization#70]
Hello,

For some reason when the package is loaded in my config/app.php all my **_resources_** route aren't working anymore.

My routes are in a Route::group and I don't need this group of routes to be translated:

_routes/web.php_
```php
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    /**
     * These routes need view-backend permission
     */
    require(__DIR__ . '/Backend/Dashboard.php');
    require(__DIR__ . '/Backend/Search.php');
    require(__DIR__ . '/Backend/Compound.php');
    require(__DIR__ . '/Backend/Access.php');
    require(__DIR__ . '/Backend/LogViewer.php');
});
```

_routes/Backend/Compound.php_

```php
 /* REST routes for a compound */
Route::resource('compound', 'Compound\CompoundController', ['except' => ['show']]);
```

When I comment this function in _Arcanedev\Localization\Routing\Router.php_, my routes work again normally.

line 42
```php
public function resource($name, $controller, array $options = [])
{
    $registrar = new ResourceRegistrar($this);

    $registrar->register($name, $controller, $options);
}
```

Any idea what's going on?

**Comment by arcanedev-maroc** [comment]
Hi,

This is why you've got the issue with resource routes:

* https://github.com/ARCANEDEV/Localization/issues/14
* https://github.com/ARCANEDEV/Localization/issues/9
* https://github.com/ARCANEDEV/Localization/issues/5

IMO, the best way to register the routes is to be explicit and avoid the usage of `resource` routes.

**EDIT:** Feel free to create a PR if you solved the `Route::resource()` issue with localized routes.
