### ISSUE TITLE
Form Input errors

### ISSUE THREAD

**Issue by devdurbs** [ARCANEDEV/Localization#71]
Hi

My routes, html templates etc are all translating fine. However, responses to form input only appear in English.

Validating form input via Requests return validation messages in English only. e.g

```php
'period' => 'required_without:days',
```

Flashing response messages from the Controller back to the form appear in English only. e.g.

```php
return back()->with('contact-confirm', trans('messages.saved_change'));
```

I'm not setting Laravel's app.locale anywhere, assuming that your lacalization takes care of that automatically. Using Laravel 5.1 and the localization settings are:

```php
'middleware' => [
    'localization-session-redirect' => true,
    'localization-cookie-redirect'  => false,
    'localization-redirect'         => true,
    'localized-routes'              => true,
    'translation-redirect'          => true,
],
```

Would appreciate some pointers.
Thanks

**Comment by arcanedev-maroc** [comment]
I've just test your case and it work fine for me (with laravel 5.1 installation).

I'm sure you forget to add the `messages.php` file into your locales folders.

### To reproduce:

##### app/Http/routes.php
```php
Route::localizedGroup(function () {
    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('form', [
        'as' => 'form.get',
        function () {
            return view('form');
        }
    ]);

    Route::post('test', [
        'as' => 'form.post',
        function (Illuminate\Http\Request $request) {
            $validator = Validator::make($request->all(), [
                'email' => 'required|email',
            ]);

            if ($validator->fails()) {
                return back()->withErrors($validator)->withInput();
            }

            return back()->with('contact-confirm', trans('messages.saved_change'));
        }
    ]);
});
```

##### resources/views/form.blade.php
```blade
<form action="{{ route('form.post') }}" method="POST">
    {{ csrf_field() }}

    <input type="text" name="email" value="{{ old('email') }}">
    <br>
    <span>{{ $errors->first('email') }}</span>
    <br>

    <button type="submit">Submit</button>

    <?php dump(session()->get('contact-confirm')); ?>
</form>
```
##### resources/lang/en/messages.php
```php
<?php

return [
    'saved_change' => '[EN] saved change',
];
```
##### resources/lang/es/messages.php
```php
<?php

return [
    'saved_change' => '[ES] saved change',
];
```

##### resources/lang/fr/messages.php

```php
<?php

return [
    'saved_change' => '[FR] saved change',
];
```

**Comment by devdurbs** [comment]
The messages.php and validation.php files are in the various lang 
directories (en, es, fr).

It seems to me that the localization settings are not available outside 
the views directory. For instance, if I dump the current language in one 
of the controller e.g
\App::getLocale()
localisation()->getCurrentLocale()

it always returns the laravel default = 'en'.

Thanks
Ray

ARCANEDEV wrote:

**Comment by arcanedev-maroc** [comment]
Did you installed the `arcanedev/localization` package properly ?

Are you using another package for localization (like translations package) ?

Try with a fresh laravel installation + `arcanedev/localization` package and see if you got the same issue.

**Comment by devdurbs** [comment]
A fresh install of Laravel is not an option.

This has all worked before and all translations in .blade documents work 
perfectly.

Both the validation and messages files have translated versions and are 
in the es and fr lang directories.

No translation files called from within controllers are working and I 
assume that your Localization facade is not being 'seen' inside controllers.

This line inside a controller returns the message in English only:
trans('messages.saved_change')

If the same line is used in the target .blade document it works fine.

If I execute this in the controller:
dd(localization()->getSupportedLocales());
I get:
#items: array:3 [▼
     "en" => Locale {#221 ▶}
     "es" => Locale {#227 ▶}
     "fr" => Locale {#237 ▶}
   ]

But if I execute this in the controller:
dump(localization()->getCurrentLocale());
I get:
"en" - no matter what language has been selected in the navigation.

Would really appreciate some pointers,
Thanks
Ray


ARCANEDEV wrote:

**Comment by arcanedev-maroc** [comment]
Sorry but i can't reproduce your issue, everything works fine for me.
