### ISSUE TITLE
https to http?

### ISSUE THREAD

**Issue by maorkavod** [ARCANEDEV/Localization#74]
Hello,
im using this package for my system,
i moved to ssl url , https.
there is an issue at least for me, lets say that im on the welcome page, 
https://test.com/en ,
 there is a button inside this page, with href '/register'
so the site is redirected to : 
https://test.com/register, but after it there is an other redirect of the package to 
http://test.com/en/register with http and not keeping the real protocol.

how can i fix this?
thanks!

**Comment by arcanedev-maroc** [comment]
I think this is related to laravel, try to check the forums like this one:
https://laracasts.com/discuss/channels/servers/force-ssl-secure-routes-in-laravel-52

**Comment by maorkavod** [comment]
Thank you, 
this solution worked for me :
http://stackoverflow.com/questions/28402726/laravel-5-redirect-to-https
