### ISSUE TITLE
how to use in AppServiceProvider ?

### ISSUE THREAD

**Issue by olipiskandar** [ARCANEDEV/Localization#75]
i have trouble to use this package in AppServiceProvider.
this my code :

```php
$mainmenu = Menu::where('position', 'mainmenu')->where('locale', \Localization::getCurrentLocale())->get();
```

only showing data with locale = en..

**Comment by arcanedev-maroc** [comment]
If you want to use a service provider, try to create a new one like `MenuServiceProvider` and register it after the `RouteServiceProvider`.

Put your code inside the `boot()` method.

But i recommend to use a [view composer](https://laravel.com/docs/5.3/views#view-composers).
