### ISSUE TITLE
Route::transGet and QueryString

### ISSUE THREAD

**Issue by itxp2008** [ARCANEDEV/Localization#76]
Hi,

Pagination not working with `Route::transGet`. 

My settings:

```php
'supported-locales'      => ['ro', 'en'],
'accept-language-header' => true,
'hide-default-in-url'    => true,
'facade'                 => 'Localization',

'route'                  => [
    'middleware' => [
        'localization-session-redirect' => true,
        'localization-cookie-redirect'  => false,
        'localization-redirect'         => true,
        'localized-routes'              => true,
        'translation-redirect'          => true,
    ],
],
```

on page `project.dev/cautari?page=2` in the language selector `localization()->getLocalizedURL($key)` returns `project.dev/en/cautari?page=2`

Without the query sting works well `project.dev/cautari` in the language selector for en is `project.dev/en/searches`

Thanks, in rest everything works well, great package

**Comment by arcanedev-maroc** [comment]
What is your laravel version ?

Can you give us the pagination code you're using to reproduce your issue ?

Or you having an issue with `localization()->getLocalizedURL($key)` ?

The `getLocalizedURL` accepts 3 arguments. What does `$key` refer to in your example ?

```php
/**
 * Returns an URL adapted to $locale.
 *
 * @param  string|bool   $locale
 * @param  string|false  $url
 * @param  array         $attributes
 *
 * @return string|false
*/
public function getLocalizedURL($locale = null, $url = null, $attributes = []);
```

**Comment by itxp2008** [comment]
Hi,

I'm using laravel 5.1

It's not just about pagination, it's about everywhere i use query strings.

Same issue on page `project.dev/cauta?query=text` in the language selector `localization()->getLocalizedURL($key)` returns just `project.dev/en/cauta?query=text` and not `project.dev/en/search?query=text`

Site wide the language selector is working perfectly including with translated routes. The key i'm using is just the other language, 'ro' when locale is 'en' and 'en' when locale is 'ro'.

The bizarre thing is when i change the `lang/[key]/routes.php`

FROM
```
[ro]
'search' => 'cauta/',
'searches' => 'cautari/'
[en]
'search' => 'search/',
'searches' => 'searches/'
```

TO
```
[ro]
'search' => 'cauta',
'searches' => 'cautari'
[en]
'search' => 'search',
'searches' => 'searches'
```

Whitout the "/" this happens

On page `project.dev/cauta?query=text` `localization()->getLocalizedURL($key)` returns `project.dev/en/search` but without the query string

On page `project.dev/en/searches?page=2` `localization()->getLocalizedURL($key)` returns just `project.dev/cautari`

One more thing, if i'm using '-' separator in tranlated routes... generating routes with `route()` doesn't work ex. `project/item/{code}-{name}` it doesn't work, just restful `project/item/{code}/{name}`

**Comment by itxp2008** [comment]
Hi

I'm giving you more details

Here you have `Http/routes.php`

```php
Event::listen('routes.translation', function ($locale, $route, $attributes) {

    if($attributes['slug']=='bucuresti' && $locale == 'en')$attributes['slug']='bucharest';
    if($attributes['slug']=='bucharest' && $locale == 'ro')$attributes['slug']='bucuresti';

    return $attributes;
});

Route::localizedGroup(function () {

    //Home
    Route::get('/', 'FrontendController@index')->name('home');

    //City
    Route::transGet('routes.city-index', 'CityController@index')->name('city-index');
    Route::transGet('routes.city-available', 'CityController@available')->name('city-available');

    //County
    Route::transGet('routes.county-index', 'CountyController@index')->name('county');

    //Area
    Route::transGet('routes.area-index', 'AreaController@show')->name('area');

    //Product
    Route::transGet('routes.product', 'ProductController@show')->name('product');

    //Search
    Route::transGet('routes.search', 'SearchController@search')->name('search');
    Route::transGet('routes.searches','SearchController@index')->name('searches');

});
```

I'm using an Event Listener for translating one city(slug = bucharest) it's the only city that has a different name in English. I don't like the 302 redirect but i didn't have a choice (if you have a cleaner/direct way to do this please leave me a hint).

Here you have `en/routes.php`

```php
return array(

    /*
    |--------------------------------------------------------------------------
    | Routes
    |--------------------------------------------------------------------------
    |
    | The following language lines contain the routes of the website
    |
    */


    'city-index' => 'products/{slug}',
    'city-available' => 'products/{slug}/available',
    'county-index' => 'products/county/{slug}',
    'area-index' => 'products/{slug}/area/{area}',
    'product' => 'products/{slug}/{idname}',
    'search' => 'search',
    'searches' => 'searches',

);
```

And `ro/routes.php`

```php
return array(

    /*
    |--------------------------------------------------------------------------
    | Routes
    |--------------------------------------------------------------------------
    |
    | The following language lines contain the routes of the website
    |
    */


    'city-index' => 'produse/{slug}',
    'city-available' => 'produse/{slug}/disponibile',
    'county-index' => 'produse/judet/{slug}',
    'area-index' => 'produse/{slug}/zona/{area}',
    'product' => 'produse/{slug}/{idphonename}',
    'search' => 'cauta',
    'searches' => 'cautari',

);
```

Now here are the results:

`project.dev` switch `en` goes to `project.dev/en`
`project.dev/?page=2` switch `en` goes to `project.dev/en?page=2`

... so here language switching and query strings and pagination works flawless

next route here things are getting confusing

`project.dev/produse/pitesti` switch `en` goes to `project.dev/en/products/pitesti` - here Translated Routes are working
`project.dev/produse/pitesti?page=2` switch `en` goes to `project.dev/en/produse/pitesti?page=2` Translated Routes aren't working and returns 404

Same thing for conty and area with paginator's query string

On the product route everything works great, no query string here

And here is the creepiest one
`project.dev/cauta?produse=query` switch `en` goes to `project.dev/en/search`
including the final one
`project.dev/cautari?page=2` switch `en` goes to `project.dev/en/searches`

In both cases here it strips out the query strings

The only differences here are the routes containing {slug}/{any parameter} behave in a way, the '/' route behaves as supposed and the static routes behave in a totally different way.

Hope it clears the situation...

**Comment by arcanedev-maroc** [comment]
Thanks @itxp2008 for the details, i'm going to test your case and try to solve it (If i've got some free time this week).

For the time being, try to check that you don't have any conflicts with your routes (for the 404 responses), for example:

```php
Route::get('user/{slug}', array( ... ));
Route::get('user/create', array( ... )); // This route will never be called because the `user/create` is matched with `user/{slug}` URI.

**Comment by itxp2008** [comment]
The 404 is returned because for that language in particular that route doesn't exist. I've had this route cascading before. I'm trying to convert this project in a multi-language one. That's why i'm using `'hide-default-in-url'    => true,` because i already have a structure in place in production. I'm just trying to add 'en' locale to my structure.
Thanks again.

**Comment by quienti** [comment]
Hi!

Any news about this problem ?
I facing to this same problem ^^

Thank you

**Comment by azeos** [comment]
I'm having the same problem. The moment a query string is added, the URL translation fails. Without it it works just fine.

Laravel 5.5
Localization 2.2.1

**routes\web.php:**
```PHP
Route::transGet('routes.activities.index', 'ActivityController@index')->name('activities.index');
````
**en\routes.php:**
```PHP
return [
    'activities.index' => 'festivals/{festival}/activities'
];
````
**es\routes.php:**
```PHP
return [
    'activities.index' => 'festivales/{festival}/actividades'
];
````
**nav1.php:**
```Blade
@foreach(Localization::getSupportedLocales() as $localeCode => $locale)
    <a rel="alternate" hreflang="{{ $localeCode }}" href="{{ Localization::getLocalizedURL($localeCode) }}">{{ $localeCode }}</a>
@endforeach
```
**nav2.php:**
```Blade
<?php parse_str($_SERVER['QUERY_STRING'], $queries) ?>
@foreach(Localization::getSupportedLocales() as $localeCode => $locale)
    <a rel="alternate" hreflang="{{ $localeCode }}" href="{{ Localization::getLocalizedURL($localeCode, url()->current(), $queries) }}">{{ $localeCode }}</a>
@endforeach
```
**URLs without query string:**
`proyect.loc/es/festivales/nombre-festival/actividades`
`proyect.loc/en/festivals/name-festival/activities`

**URLs with query string:**
`proyect.loc/es/festivales/nombre-festival/actividades?activityType=workshops`
`proyect.loc/en/festivales/nombre-festival/actividades`

As you can see in `nav2.php`, I tried to pass directly the `attributes` parameter but it didn't work.

This problem exists in the original package: https://github.com/mcamara/laravel-localization/issues/420

**EDIT:**
Translating only the current URL and manually adding the query string works:
```Blade
@foreach(Localization::getSupportedLocales() as $localeCode => $locale)
    <a rel="alternate" hreflang="{{ $localeCode }}" href="{{ Localization::getLocalizedURL($localeCode, url()->current()) }}{{ $_SERVER['QUERY_STRING'] ? '?' . $_SERVER['QUERY_STRING'] : '' }}">{{ $localeCode }}</a>
@endforeach
```

Thanks for the package and thanks for your help.
