### ISSUE TITLE
Method aliasMiddleware does not exist

### ISSUE THREAD

**Issue by oscar1600** [ARCANEDEV/Localization#80]
- Localization Version: 1.0.1
- Laravel Version: 5.3
- PHP Version: 5.7

### Description:

When i tried to publish config

php artisan vendor:publish --provider="Arcanedev\Localization\LocalizationServiceProvider"

appear this error

[BadMethodCallException]  Method aliasMiddleware does not exist. 

### Steps To Reproduce:

1.- $ composer require arcanedev/localization
2.- set Arcanedev\Localization\LocalizationServiceProvider::class in providers array 
3.- set  use \Arcanedev\Localization\Traits\LocalizationKernelTrait; in kernel
4.- php artisan vendor:publish --provider="Arcanedev\Localization\LocalizationServiceProvider"

how to solve this error?

**Comment by arcanedev-maroc** [comment]
You need to lock the version with `"arcanedev/localization": "~0.8"`

The `"arcanedev/localization": "~1.0"` is for `Laravel 5.4`

**Comment by arcanedev-maroc** [comment]
I'm going to add [something like](https://github.com/ARCANEDEV/Breadcrumbs/blob/master/_docs/2-Version-Compatibility.md) this to avoid any confusion about what version to use.

Thanks @oscar1600 for your feedback 👍

**Comment by oscar1600** [comment]
Thanks for your reply
