### ISSUE TITLE
Route translation in language menu won't work for nested groups

### ISSUE THREAD

**Issue by FSAA** [ARCANEDEV/Localization#84]
- Localization Version: 0.8.
- Laravel Version: 5.3.
- PHP Version: 5.6.

Here is our route file. The home page url is translated correctly since it's not in the nested group, but all the others are not working 

Here are the URL I'm obtaining when using the getLocalizedURL() method.

https://simulovins_v2.dev.fsaa.ulaval.ca/fr/mes-simulations/liste
https://simulovins_v2.dev.fsaa.ulaval.ca/en/mes-simulations/liste

The last one is suppose to be  : 
https://simulovins_v2.dev.fsaa.ulaval.ca/en/simulations/list
(if I type it directly it's working)

Sorry i tried to use the insert code snippet but it was not working so my code is in the attached file.
[code.txt](https://github.com/ARCANEDEV/Localization/files/764991/code.txt)

**Comment by FSAA** [comment]
So is there any solution to this problem?

**Comment by arcanedev-maroc** [comment]
Sorry @FSAA, i've been busy lately and i forgot to answer you.

Can you show me the translated routes in the `lang` folder ?

You can avoid the prefix group by doing something like this:

```php
// Routes

Route::group(['middleware' => 'sentinel.auth'], function () {
    Route::localizedGroup(function() {
        Route::transGet('routes.home', 'UserController@home')->name('home');

        Route::transGet('routes.simulations.list', 'SimulationController@listAction')->name('simulations.list');
        Route::transGet('routes.simulations.add', 'SimulationController@add')->name('simulations.add');
        Route::transPost('routes.simulations.create', 'SimulationController@create')->name('simulations.create');
        Route::transGet('routes.simulations.edit', 'SimulationController@edit')->name('simulations.edit');
        Route::transPatch('routes.simulations.update', 'SimulationController@update')->name('simulations.update');
        Route::transDelete('routes.simulations.delete', 'SimulationController@delete')->name('simulations.delete');
        Route::transGet('routes.simulations.overview', 'SimulationController@overview')->name('simulation.overview');
    }); 
});

// Lang: en/routes.php

return [
    'simulations' => [
        'list'     => 'simulations/list',
        'add'      => 'simulations/add',
        'create'   => 'simulations/create',
        'overview' => 'simulations/{simulation}/overview', // You can rename it to show as a key and remove the `/overview` from the uri
        'edit'     => 'simulations/{simulation}/edit',
        'update'   => 'simulations/{simulation}/update',
        'delete'   => 'simulations/delete',
    ],
];

// Samething for fr
```

And check in your `localization` config file that the `localized-routes`, `localization-session-redirect`, `localization-redirect` are enabled.

If you have some difficulty with `getLocalizedURL` method, try to use [getUrlFromRouteName()](https://github.com/ARCANEDEV/Localization/blob/master/src/Localization.php#L427) instead.

> I need to check it later to see if it's a bug or not

Hope this helps you & thanks for using this package 👍

**Comment by mkwsra** [comment]
@arcanedev-maroc Buddy, this problem is since that macamara package.
I would really appreciate it if you think there is any way to prevent this odd behavior, it's only when you are on any page other then En and trying to navigate to the English page. for sure from the navbar, or let's say `getLocalizedUrl()` function.
I have an open issue there since 2015.
https://github.com/mcamara/laravel-localization/issues/174

And I will try to help you since I need it so bad.

Cheers!

**Comment by arcanedev-maroc** [comment]
Hi @mkwsra, is your issue is also related to this package `arcanedev/localization` ?

> TBH, i didn't test a not utf-8 character with this package.

**Comment by mkwsra** [comment]
@arcanedev-maroc  Yes, :)  I'm using yours for a long time.

However, yesterday I solved the routes being stuck issue
 :) I'll make a PR in a sec
