### ISSUE TITLE
Optional route parameters

### ISSUE THREAD

**Issue by melokki** [ARCANEDEV/Localization#86]
Hi @arcanedev-maroc 

I have a route with 2 parameters, but I would like to make those parameters optional. When there are no parameters I show a different view.
I can't find anything in your documentation about optional route parameters.

How can I do that?

**Comment by arcanedev-maroc** [comment]
Hi @melokki,

I think your question is related to laravel framework and not to the localization package.

Can you be more specific what you want to achieve ?

Please check the laravel documentation and especially the routing section.

**Comment by melokki** [comment]
Hello.
Nevermind, I figured out a solution.
