### ISSUE TITLE
[AJAX] UnsupportedLocaleException

### ISSUE THREAD

**Issue by karolisbarkauskas** [ARCANEDEV/Localization#88]
- Localization Version: latest
- Laravel Version: 5.3
- PHP Version: 5.6 - 7.1 (can be recreated on both versions)

### Description:
Exception Class:	Arcanedev\Localization\Exceptions\UnsupportedLocaleException
Exception Message:	Locale 'get_results_count' is not in the list of supported locales.

### Steps To Reproduce: 
get_results_count is ajax call

**Comment by arcanedev-maroc** [comment]
The first segment in URL is the `locale`.

If you put your API (AJAX) routes inside the localized group, you need to specify the locale like this:

`http://your-site.com/en/get_results_count` 

instead of 

`http://your-site.com/get_results_count`

**Solution 1:** Extract your API routes outside the localized routes.
**Solution 2:** Add a locale to your ajax call like this `http://your-site.com/en/get_results_count`.

> Note: The locale `en` is just an example, you specify a locale that is supported in your config file.

**Comment by karolisbarkauskas** [comment]
Is it possible to redirect to default language if this error happens? 
Because at the moment entire site stops working untill you go to proper URL

**Comment by arcanedev-maroc** [comment]
The redirection works perfectly when you visit the unlocalized URL with a browser because it can handle it.

The AJAX doesn't handle the redirection.

**Comment by arcanedev-maroc** [comment]
Hi @HeatedPillow, i think i've a good news for you.

I added a new feature to set ignored uri from the localization: https://github.com/ARCANEDEV/Localization/blob/master/config/localization.php#L33-L40

And it's released as `v1.0.4` for Laravel `v5.4`.

if you set `ignored-uri` value like this:

```php
'ignored-uri' => [
    'get_results_count',
],
```

You can perform your AJAX calls with these endpoints:

```php
'http://your-site.com/{locale}/get_results_count' // Works
'http://your-site.com/get_results_count'          // Works

// replace {locale} with a supported locale
```

**KEEP IN MIND:** The localization features is not going to work properly with ignored uris.

👍

**Comment by karolisbarkauskas** [comment]
Any chance for Laravel 5.3 support?

Thanks for the good news :)

**Comment by arcanedev-maroc** [comment]
I can't do that because the `0.8` branch is closed for any new features, only bug fixes unfortunately.

**Comment by karolisbarkauskas** [comment]
Thanks, upgraded my framework to 5.4 and everything seems to be working just fine! Thanks again
