### ISSUE TITLE
Laravel route name odd behaviour

### ISSUE THREAD

**Issue by Reached** [ARCANEDEV/Localization#91]
- Localization Version: 1.0.0
- Laravel Version: 5.4.16
- PHP Version: 7.0.0

### Description:
First of all, great package, well done! 

I am observing a funny behaviour when I use  route name like so:

```php
Route::transPost('routes.registerLandlord', function() {
    return 'Yay!';
})->name('register-landlord');
```

The url for this route is translated into this: http://mydomain.dev/en/routes.registerLandlord instead of http://mydomain.dev/en/register-landlord

The route works, but it defeats the purpose of translating the routes a bit imo :)

### Steps To Reproduce:

Create a route and add ->name('something') to it, when you refer to the name in your views (e.g. `<a href="{{ route('something') }}">Some string</a>` it will show the "issue" 

Thank you!

**Comment by arcanedev-maroc** [comment]
I recommend to use translation names like `routes.register-landlord` instead of `routes.registerLandlord`.

And also, check that you're not missing the routes files for each your `resource/lang/{locale}` folder.

For example:

```php
// resources/lang/en/routes.php

return [
    'register-landlord' => 'register-landlord',
    // ...
];
```

```php
// resources/lang/fr/routes.php
return [
    'register-landlord' => 'enregistrer-propritetaire',
];
```

**Comment by arcanedev-maroc** [comment]
I've just tested the package with the default config and i didn't reproduce the issue.

I think you've missed the translations.

**Comment by Reached** [comment]
Oh wow.. I guess you are completely right, I just double checked my route translations, and a string were missing. Now its working as intended! Sorry for the inconvenience, and for taking the time to help Thanks for the advice on the route names too, I guess that is a lot more readable actually :)

**Comment by arcanedev-maroc** [comment]
You're welcome 👍
