### ISSUE TITLE
Redirect after language change

### ISSUE THREAD

**Issue by karolisbarkauskas** [ARCANEDEV/Localization#97]
### Description:
Hello,

Lets say I have http://project.dev/super_link_one 

I decide to change language to another and I get redirected to home page. 

Can I be redirected to http://project.dev/lt/translated_link (lt -> new locale) ?

Is this supported by this package?

Thanks

**Comment by arcanedev-maroc** [comment]
Yes you can.

**Comment by karolisbarkauskas** [comment]
Can I see mini example of that? 

Would really appreciate that!

**Comment by arcanedev-maroc** [comment]
First, check the [documentation](https://github.com/ARCANEDEV/Localization/blob/master/_docs/3-Usage.md) to understand how it works and see if this is what you need in your application.

After that there are many ways to redirect from `unlocalized` url to `localized` one

```php
// routes/web.php

// Localized routes
Route::localizedGroup(function () {
    Route::get('/', [
        'as'   => 'public::home'
        'uses' => 'PageController@index'
    ]);
});

// Unlocalized routes
Route::get('super_link_one', function () {
    return redirect()->route('public::home');
});
```

Check can also check the [answered questions](https://github.com/ARCANEDEV/Localization/issues?utf8=%E2%9C%93&q=label%3Aquestion) for more details.
